SELECT 
  SYSTEM_TABLE_SCHEMA,
  SYSTEM_TABLE_NAME,
  SYSTEM_COLUMN_NAME,
  DATA_TYPE,
  LENGTH,
  NUMERIC_SCALE,
  CCSID
FROM QSYS2.SYSCOLUMNS
WHERE SYSTEM_TABLE_SCHEMA = 'WWDCF'
  AND SYSTEM_TABLE_NAME   = 'EMMSTR'
  AND SYSTEM_COLUMN_NAME IN ('EBEGDTE','EMEFFDT')





SELECT t1.EHEMP AS EMPLOYEE_ID,
    t2.EMRNAM AS EMPLOYEE_NAME,
    0 AS HOURS_WORKED,
    t1.EHSHFT AS SHIFT,
    t1.EHHDPT AS DEPARTMENT,
    t1.EHSTRT AS ACTUAL_START_TIME,
    t1.EHSTOP AS ACTUAL_STOP_TIME,
    t1.EHDATE AS TRANSACTION_DATE,
    t1.EHPLNT AS EMPLOYEE_FACILITY_NUMBER,
    t1.EHHGRP AS EMPLOYEE_GROUP
FROM WWDCF.HDMECH T1
JOIN WWDCF.EMMSTR T2 
    ON T1.EHEMP = T2.EMEMPL  
WHERE T1.EHDATE BETWEEN ? AND ?  

UNION ALL

SELECT t1.LBEMP AS EMPLOYEE_ID,
    t2.EMRNAM AS EMPLOYEE_NAME,
    t1.LBPHRS AS HOURS_WORKED,
    t1.LBSHFT AS SHIFT,
    t1.LBDEPT AS DEPARTMENT,
    t1.LBASTR AS ACTUAL_START_TIME,
    t1.LBASTP AS ACTUAL_STOP_TIME,
    t1.LBDATE AS TRANSACTION_DATE,
    t1.LBFAC AS EMPLOYEE_FACILITY_NUMBER,
    t1.LBHGRP AS EMPLOYEE_GROUP
FROM WWDCF.PYREXPH T1
JOIN WWDCF.EMMSTR T2 
    ON T1.LBEMP = T2.EMEMPL  
WHERE T1.LBDATE BETWEEN ? AND ?  

ORDER BY TRANSACTION_DATE DESC, EMPLOYEE_GROUP, EMPLOYEE_ID