Select s1.ITNBR, s1.HOUSE, S1.MOHTQ, S1.WHSLC, S1.ITCLS, s1.QTSYR,s1.MPUPQ open_po, s1.USEYR qty_used_this_year, s1.PLREQ open_co,s1.QTSMO qty_sold_this_period, s1.RECMO qty_received_this_period,
s1.B2Z95S, s1.ITDSC, s1.TIHIUNLD, s1.PICKPUT, s1.ITMCLSID, s1.UNITSWIDE, s1.UNITLAYERS, s1.UNITSDEEP, 
s1.SCOOPQTY, s1.SKIDSIZE, s1.QTYCR, s1.NBSEAT, s1.CRTWIN, s1.CRTLIN, s1.CRTHIN, s1.PRDWIN, 
s1.PRDHIN, s1.PRDLIN, s1.ITMWEGHT,s2.OPEN_PO

from (SELECT t4.ITNBR, t2.HOUSE, t2.MOHTQ, t2.WHSLC, t2.ITCLS, t2.QTSYR, t4.B2Z95S, 
t4.ITDSC, t1.TIHIUNLD, t1.PICKPUT, t1.ITMCLSID, t1.UNITSWIDE, t1.UNITLAYERS, t1.UNITSDEEP, 
t1.SCOOPQTY, t1.SKIDSIZE, t3.QTYCR, t3.NBSEAT, t3.CRTWIN, t3.CRTLIN, t3.CRTHIN, t3.PRDWIN, 
t3.PRDHIN, t3.PRDLIN, t3.ITMWEGHT, t2.MPUPQ, t2.USEYR, t2.PLREQ, t2.QTSMO, t2.RECMO
FROM AFILELIB.ITBEXT t1, AMFLIBA.ITEMBL t2, AFILELIB.ITMEXT t3, AMFLIBA.ITMRVA t4
WHERE t1.ITNBR = t4.ITNBR AND t2.HOUSE = t1.HOUSE AND t2.ITNBR = t1.ITNBR AND 
t2.ITNBR = t4.ITNBR AND t2.ITCLS = t4.ITCLS AND t3.ITNBR = t1.ITNBR AND t3.ITNBR = t2.ITNBR AND 
t3.ITNBR = t4.ITNBR AND t4.STID = t1.HOUSE AND t1.HOUSE='335') as s1


LEFT JOIN

(SELECT c.ITNBR, SUM(c.QTYOR) AS OPEN_PO
FROM AFILELIB.ITBEXT a, AFILELIB.ITMEXT b, AMFLIBA.POITEM c, AMFLIBA.POMAST d, AMFLIBA.VENNAML0 e
WHERE a.ITNBR = b.ITNBR AND c.ITNBR = b.ITNBR AND c.ORDNO = d.ORDNO AND 
d.VNDNR = e.VNDRVM AND c.HOUSE = a.HOUSE AND d.HOUSE = c.HOUSE
AND d.HOUSE='335' AND d.PSTTS NOT IN ('10','20','30') and c.DUEDT  
BETWEEN  int('1'||substr(trim(char(CURRENT DATE - 30 days)),3,2)||substr(trim(char(CURRENT DATE- 30 days)),6,2)||substr(trim(char(CURRENT DATE- 30 days)),9,2)) 
AND int('1'||substr(trim(char(CURRENT DATE + 360 days)),3,2)||substr(trim(char(CURRENT DATE + 360 days)),6,2)||substr(trim(char(CURRENT DATE + 360 days)),9,2))
GROUP BY C.ITNBR) as s2

on s1.ITNBR = s2.ITNBR

WHERE  s1.ITCLS LIKE 'Z%' and s1.ITCLS not LIKE '%K' and (s1.MOHTQ<>0 or s2.OPEN_PO<>0) and s1.PICKPUT in ('PALLT','UPH')