SELECT t1.LBEMP,
    t2.EMRNAM,
    t1.LBPHRS,
    t1.LBSHFT,
    t1.LBDEPT,
    t1.LBOPYC,
    t1.LBASTR,
    t1.LBASTP,
    t1.LBDATE
FROM WWDCF.PYREXPH T1
JOIN WWDCF.EMMSTR T2 
  ON T1.LBEMP = T2.EMEMPL  
WHERE t1.LBEMP = '43344'
FETCH FIRST 10 ROWS ONLY