SELECT t1.ORDNO, TRIM(t1.ITNBR) AS ITNBR, t1.HOUSE, T1.ITCLS, T1.DUEDT, T1.VNDNR, T1.PSTTS, t3.VNDRVM, t3.VNNMVM, sum(t1.QTYOR) as Open_PO
FROM (SELECT t1.ORDNO, t1.ITNBR, t1.HOUSE, T1.ITCLS, T1.DUEDT, T1.VNDNR, T2.PSTTS, T1.QTYOR
    FROM Wholesale_Purchasing_AFI.POITEM t1, Wholesale_Purchasing_AFI.POMAST t2
    WHERE t1.ORDNO = t2.ORDNO AND t2.HOUSE = t1.HOUSE AND (t1.HOUSE='335') AND T2.PSTTS IN ('30')) AS T1
    LEFT JOIN AMFLIBA.VENNAML0 t3 on t1.VNDNR=t3.VNDRVM
group by t1.ORDNO, TRIM(t1.ITNBR),t1.HOUSE,T1.ITCLS,T1.DUEDT,T1.VNDNR,T1.PSTTS, t3.VNDRVM,t3.VNNMVM
ORDER BY t1.ORDNO, trim(t1.ITNBR)