SELECT *
FROM AFILELIB.CODATAT  
where ordno = 'C795769' and ITNBR = '3300316'


SELECT 
    ORDNO, 
    ITNBR, 
    ITMSQ,
    LISTAGG(TRIM(ICMT1), ', ') WITHIN GROUP (ORDER BY CMTSQ) AS ICMT1,
    LISTAGG(TRIM(ICMT2), ', ') WITHIN GROUP (ORDER BY CMTSQ) AS ICMT2,
    LISTAGG(TRIM(ICMT3), ', ') WITHIN GROUP (ORDER BY CMTSQ) AS ICMT3
FROM AFILELIB.CODATAT
where ordno = 'C795769' and ITNBR = '3300316'
GROUP BY ORDNO, ITNBR, ITMSQ