SELECT 
	   [equipment_id] AS [Equipment ID]
      ,[Inventory Type]
      ,[item_number] AS [Item #]
      ,[pomvendornum] AS [Vendor#]
      ,[Vendor NAME] AS [Vendor Name]
      ,[Vendor Import Domestic Flag]
      ,[Vendor Country]
      ,[Shipped Pcs]
      ,[Received Pcs Without Damage]
      ,[Damaged Pcs]
      ,[Shortage Pcs]
      ,[Overage Pcs]
      ,[Total Received Pcs]
      ,[PO]
      ,[On Shipped ASN Record]
	  ,[Percent_Complete]
      ,[Percent_Complete] / 100 AS [% Complete]
	  --,[Damaged Pcs] / [Shipped Pcs] AS [% Damage]
	  --,[Overage Pcs] / [Shipped Pcs] AS [% Overage] -- Change to Total Received
	  --,[Shortage Pcs] / [Shipped Pcs] AS [% Shortage]
      ,[Expected_arrival] AS [Expected Arrival]
      ,[asn_number] AS [ASN #]
      ,[Warehouse ID] AS [Destination DC]
      ,[Entered_yard] AS [Entered Yard]
      ,[Exited_yard] AS [Exited Yard]
      ,[Load Type]
      ,[Actual Ship Date]
      ,[Origin DC]
  FROM [PowerBI_Distribution].[VendorShipmentDetails]