SELECT t1.ORDNO, TRIM(t1.ITNBR) AS ITNBR, t1.HOUSE,T1.ITCLS,T1.DUEDT,T1.VNDNR,T1.PSTTS, t3.VNDRVM,t3.VNNMVM, T1.ITDSC, T1.Unit_CBM,
CASE
    WHEN T1.ITCLS NOT LIKE 'Z%' THEN 'RP'
    WHEN T1.ITNBR LIKE '100-%' THEN 'CG'
    WHEN REGEXP_LIKE(TRIM(T1.ITNBR), '^[1-9U]') THEN 'UPH'
    --WHEN SUBSTR(TRIM(T1.ITNBR),1,1) IN ('1','2','3','4','5','6','7','8','9','U') THEN 'UPH'
    WHEN SUBSTR(TRIM(T1.ITNBR),1,1) IN ('A') AND T1.Unit_CBM >= 0.3 THEN 'CG'
    WHEN SUBSTR(TRIM(T1.ITNBR),1,1) IN ('A','L','R','Q') THEN 'ACCESSORY'
    WHEN LENGTH(TRIM(t1.ITNBR)) = 6 AND SUBSTR(TRIM(T1.ITNBR),1,1) ='M' THEN 'ACCESSORY'
    ELSE 'CG' END AS PRODUCT,
CASE
    WHEN T1.PSTTS IN ('20') THEN 'On-Order: New ASN Pending by Vendor'
    WHEN T1.PSTTS IN ('30') THEN 'In-Transit: New ASN Accepted by Buyer'
    WHEN T1.PSTTS IN ('40') THEN 'Rc. to Stk: PO is in Receipt To Stock Status'
    WHEN T1.PSTTS IN ('50') THEN 'Receiver: PO is in Receiver Status'
    ELSE 'Check' END AS PO_STATUS,
SUM(t1.QTYOR) as Open_PO,
CAST(SUM(T1.Product_CBM) AS DECIMAL(10,2)) AS Product_CBM
FROM (SELECT t1.ORDNO, t1.ITNBR,t1.HOUSE,T1.ITCLS,T1.DUEDT,T1.VNDNR,T2.PSTTS, T1.QTYOR, T1.ITDSC,CAST(T3.B2Z95S*0.028317 AS DECIMAL(10,2)) AS Unit_CBM, T3.B2Z95S*0.028317*T1.QTYOR AS Product_CBM
FROM AMFLIBA.POITEM t1, AMFLIBA.POMAST t2, AMFLIBA.ITMRVA AS T3
WHERE t1.ORDNO = t2.ORDNO AND t2.HOUSE = t1.HOUSE AND t1.ITNBR = T3.ITNBR AND T1.HOUSE = T3.STID AND (t1.HOUSE='335') AND T2.PSTTS IN ('20','30','40','50')  AND t1.DUEDT >= '1240101'
) AS T1
LEFT JOIN AMFLIBA.VENNAML0 t3 on t1.VNDNR=t3.VNDRVM
group by t1.ORDNO, TRIM(t1.ITNBR),t1.HOUSE,T1.ITCLS,T1.DUEDT,T1.VNDNR,T1.PSTTS, t3.VNDRVM,t3.VNNMVM, T1.ITDSC, T1.Unit_CBM,
CASE
    WHEN T1.ITCLS NOT LIKE 'Z%' THEN 'RP'
    WHEN T1.ITNBR LIKE '100-%' THEN 'CG'
    WHEN SUBSTR(TRIM(T1.ITNBR),1,1) IN ('1','2','3','4','5','6','7','8','9','U') THEN 'UPH'
    WHEN SUBSTR(TRIM(T1.ITNBR),1,1) IN ('A') AND T1.Unit_CBM >= 0.3 THEN 'CG'
    WHEN SUBSTR(TRIM(T1.ITNBR),1,1) IN ('A','L','R','Q') THEN 'ACCESSORY'
    WHEN LENGTH(TRIM(t1.ITNBR)) = 6 AND SUBSTR(TRIM(T1.ITNBR),1,1) ='M' THEN 'ACCESSORY'
    ELSE 'CG' END,
CASE
    WHEN T1.PSTTS IN ('20') THEN 'On-Order: New ASN Pending by Vendor'
    WHEN T1.PSTTS IN ('30') THEN 'In-Transit: New ASN Accepted by Buyer'
    WHEN T1.PSTTS IN ('40') THEN 'Rc. to Stk: PO is in Receipt To Stock Status'
    WHEN T1.PSTTS IN ('50') THEN 'Receiver: PO is in Receiver Status'
    ELSE 'Check' END
ORDER BY t1.ORDNO, trim(t1.ITNBR)