-- ON HAND IN WHSE335 ON DSN=AFIPROD
SELECT a.ITNBR,a.HOUSE, a.ITCLS, a.MOHTQ, b.PAMNT "UP($USD)",
CASE
    WHEN a.ITCLS NOT LIKE 'Z%' THEN 'RP'
    WHEN a.ITNBR LIKE '100-%' THEN 'CG'
    WHEN SUBSTR(TRIM(a.ITNBR),1,1) IN ('1','2','3','4','5','6','7','8','9','U') THEN 'UPH'
    WHEN SUBSTR(TRIM(a.ITNBR),1,1) IN ('A') AND Z.B2Z95S >= 0.3 THEN 'CG'
    WHEN SUBSTR(TRIM(a.ITNBR),1,1) IN ('A','L','R','Q') THEN 'ACCESSORY'
    WHEN LENGTH(TRIM(a.ITNBR)) = 6 AND SUBSTR(TRIM(a.ITNBR),1,1) ='M' THEN 'ACCESSORY'
ELSE 'CG' END AS Product,
(CASE 
    WHEN b.PAMNT IS NULL AND a.ITCLS NOT LIKE 'Z%' THEN 0
	WHEN b.PAMNT IS NULL AND a.ITCLS LIKE 'Z%' THEN a.MOHTQ*50
	ELSE a.MOHTQ*b.PAMNT END) as "AMT($USD)"
FROM 
(SELECT T1.ITNBR,T1.HOUSE, T1.ITCLS, T1.MOHTQ, T1.WHSLC, T2.ITDSC    
FROM AMFLIBA.ITEMBL T1, AMFLIBA.ITMRVA T2, AMFLIBA.WHSMST T3 
WHERE  T2.ITCLS = T1.ITCLS AND T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND ((T1.HOUSE='335') AND (T1.MOHTQ<>0))
ORDER BY T1.ITNBR) as a
LEFT JOIN (SELECT PRICE.PITEM, PRICE.PAMNT FROM AFILELIB.PRICE PRICE WHERE PRICE.PRICCD='FOBARC' ORDER BY PRICE.PITEM) as b 
ON a.ITNBR = b.PITEM 
LEFT JOIN (SELECT a1.ITNBR, a1.B2Z95S FROM AMFLIBA.ITMRVA AS a1 WHERE a1.STID IN ('335')) AS Z 
ON a.ITNBR = Z.ITNBR 