import pandas as pd
import time

def run(dfs):
    print("Executing a10_item_unique_list...")
    start_time = time.time()
    
    # --- STEP 1: Load Item_Master (Col A -> Col F) ---
    dict_master = {}
    if 'Item_Master' in dfs and not dfs['Item_Master'].empty:
        df_master = dfs['Item_Master']
        col_a = df_master.columns[0]
        # Look for the product column generated by a09
        col_f = 'Product' if 'Product' in df_master.columns else (df_master.columns[5] if len(df_master.columns) > 5 else df_master.columns[-1])
        
        df_master[col_a] = df_master[col_a].astype(str).str.strip()
        df_master[col_f] = df_master[col_f].astype(str).str.strip().str.upper()
        
        dict_master = df_master.drop_duplicates(subset=[col_a]).set_index(col_a)[col_f].to_dict()

    # --- STEP 2: Aggregate OnHand (Sum Col B by Col A) ---
    dict_oh = {}
    if 'OnHand' in dfs and not dfs['OnHand'].empty:
        df_oh = dfs['OnHand']
        col_a = df_oh.columns[0]
        col_b = df_oh.columns[1]
        
        df_oh[col_a] = df_oh[col_a].astype(str).str.strip()
        df_oh[col_b] = pd.to_numeric(df_oh[col_b], errors='coerce').fillna(0)
        
        dict_oh = df_oh.groupby(col_a)[col_b].sum().to_dict()

    # --- STEP 3: Aggregate Yard (Sum Col N by Col K) ---
    dict_yard = {}
    if 'Yard' in dfs and not dfs['Yard'].empty:
        df_yard = dfs['Yard']
        col_k = 'Item Number' if 'Item Number' in df_yard.columns else df_yard.columns[10]
        col_n = 'Qty Remaining' if 'Qty Remaining' in df_yard.columns else df_yard.columns[13]
        
        df_yard[col_k] = df_yard[col_k].astype(str).str.strip()
        df_yard[col_n] = pd.to_numeric(df_yard[col_n], errors='coerce').fillna(0)
        
        dict_yard = df_yard.groupby(col_k)[col_n].sum().to_dict()

    # --- STEP 4: Collect Unique Items from all specified sheets ---
    unique_items = set()
    target_headers = ["item_number", "ITNBR", "spdItem", "Item Number", "ORDNO"]
    
    src_sheet_names = ["OnHand", "Yard", "OpenPO", "Firmed_Planned_PO", "CustomerOrder"]
    
    for s_name in src_sheet_names:
        if s_name in dfs and not dfs[s_name].empty:
            df_temp = dfs[s_name]
            for col in df_temp.columns:
                if str(col).strip().lower() in [h.lower() for h in target_headers]:
                    items = df_temp[col].dropna().astype(str).str.strip().tolist()
                    unique_items.update(items)

    if "" in unique_items:
        unique_items.remove("")

    # --- STEP 5: Sort and Populate Target Sheets ---
    item_list = sorted(list(unique_items))
    
    if item_list:
        print(f"Found {len(item_list)} unique items. Updating 'ItemBalance_by_Pieces' in memory...")
        
        res_data = []
        for item in item_list:
            # Fallback to CG if not found, consistent with summary
            prod = dict_master.get(item, "CG")
            oh_val = dict_oh.get(item, 0.0)
            yard_val = dict_yard.get(item, 0.0)
            res_data.append([item, prod, oh_val, yard_val])
            
        df_co = pd.DataFrame(res_data, columns=['Item', 'Product', 'OnHand', 'Yard'])
        dfs['ItemBalance_by_Pieces_Data'] = df_co
    else:
        print("No unique items found.")

    elapsed_time = time.time() - start_time
    print(f"a10_item_unique_list completed in {elapsed_time:.2f} seconds.")