WITH soldto as (
  select t.COMNO,
         t.CUSNO,
         t.CUSNM,
         t.CUSA1
  FROM AFILELIB.TSITIN as t



),
    shipto AS (
    SELECT
        VARCHAR(t.COMNO) AS COMNO,
        VARCHAR(t.CUSNO) AS CUSNO,
        VARCHAR(TRIM(t.SHPNO)) AS SHPNO,
        TRIM(t.SHPNM) || '(' || VARCHAR(t.CUSNO) || '/' || TRIM(VARCHAR(t.SHPNO)) || ')' AS CustomerName,
        TRIM(t.SHIP1) || ' ' || TRIM(t.SHIP2) AS Address,
        TRIM(t.SHIP3) || ',' || TRIM(t.SHPST) || ' ' ||  TRIM(t.SHPZP) AS CityStateZip,
        t.SCTYN,
        t.CCNNM
    FROM AFILELIB.ASHPMASJ AS t
),
po AS (
    SELECT
        VARCHAR(t.HOUSE) AS HOUSE,
        VARCHAR(t.ORDNO) AS ORDNO,
        VARCHAR(t.VNDNR) AS VNDNR,
        VARCHAR(t.PSTTS) AS PSTTS,
        VARCHAR(t.UU25PM) AS UU25PM
    FROM AMFLIBA.POMAST AS t
    WHERE t.HOUSE IN ('C','C35') AND t.PSTTS = '30'
),
TSITIN AS (
SELECT
        CASE
            WHEN TRIM(VARCHAR(ITINVR)) IS NULL OR TRIM(VARCHAR(ITINVR)) = '' THEN '00'
            ELSE TRIM(VARCHAR(ITINVR))
        END AS ITINVR,

        CASE
            WHEN TRIM(VARCHAR(ITORNO)) IS NULL OR TRIM(VARCHAR(ITORNO)) = '' THEN '00'
            ELSE TRIM(VARCHAR(ITORNO))
        END AS ITORNO,

        CASE
            WHEN TRIM(VARCHAR(ITWHSE)) IS NULL OR TRIM(VARCHAR(ITWHSE)) = '' THEN '00'
            ELSE TRIM(VARCHAR(ITWHSE))
        END AS ITWHSE,

        CASE
            WHEN TRIM(VARCHAR(ITCSNO)) IS NULL OR TRIM(VARCHAR(ITCSNO)) = '' THEN '00'
            ELSE TRIM(VARCHAR(ITCSNO))
        END AS ITCSNO,

        CASE
            WHEN TRIM(VARCHAR(ITSPNO)) IS NULL OR TRIM(VARCHAR(ITSPNO)) = '' THEN '00'
            ELSE TRIM(VARCHAR(ITSPNO))
        END AS ITSPNO,

        CASE
            WHEN TRIM(VARCHAR(ITPONO)) IS NULL OR TRIM(VARCHAR(ITPONO)) = '' THEN '00'
            ELSE TRIM(VARCHAR(ITPONO))
        END AS ITPONO

    FROM AFILELIB.TSITIN
    WHERE ITWHSE IN ('C','C35')
    GROUP BY ITINVR, ITORNO, ITWHSE, ITCSNO, ITSPNO, ITPONO
)

SELECT
    COALESCE(TRIM(VARCHAR(t.ININVR)), '00') AS InvNbr,
    COALESCE(TRIM(VARCHAR(t.INORNO)), '00') AS OrderNbr,
    COALESCE(TRIM(VARCHAR(t.INIVDT)), '00') AS InvoiceDate,
    COALESCE(TRIM(VARCHAR(t.INIVAM)), '00') AS InvoiceValue,
    COALESCE(TRIM(VARCHAR(t.INIDAM)), '00') AS InvoiceDiscount,
    COALESCE(TRIM(VARCHAR(t.INORVL)), '00') AS OrderValue,
    COALESCE(TRIM(VARCHAR(t.ININSL + t.INIDAM)), '00') AS BaseValue,
    COALESCE(TRIM(VARCHAR(t.INCONO)), '00') AS Company,
    COALESCE(TRIM(VARCHAR(t.INCSNO)), '00') AS CustomerNumber,
    COALESCE(TRIM(VARCHAR(t.INPONO)), '00') AS PurchaseOrder,
    COALESCE(t.INTMDS, ' ') AS TermsDesc,
    COALESCE(TRIM(VARCHAR(t.INORDT)), '00') AS OrderDate,
    COALESCE(TRIM(VARCHAR(t.INRQDT)), '00') AS RequestDate,
    COALESCE(t.INSHIN, ' ') AS ShipInstruction,
    COALESCE(TRIM(VARCHAR(t.INWHSE)), '00') AS Warehouse,
    ts.ITSPNO AS ShipToNbr,
    s.CustomerName,
    s.Address,
    s.CityStateZip,
    s.SCTYN,
    s.CCNNM
FROM AFILELIB.TSININ AS t
LEFT JOIN TSITIN AS ts
    ON COALESCE(TRIM(VARCHAR(t.ININVR)), '00') = ts.ITINVR
   AND COALESCE(TRIM(VARCHAR(t.INORNO)), '00') = ts.ITORNO
   AND COALESCE(TRIM(VARCHAR(t.INWHSE)), '00') = ts.ITWHSE
LEFT JOIN shipto AS s
    ON VARCHAR(s.COMNO) = COALESCE(TRIM(VARCHAR(t.INCONO)), '00')
   AND VARCHAR(s.CUSNO) = COALESCE(TRIM(VARCHAR(t.INCSNO)), '00')
   AND VARCHAR(s.SHPNO) = ts.ITSPNO
WHERE t.INWHSE IN ('C','C35')
  AND t.INSHIN IN (
        SELECT DISTINCT VARCHAR(po.ORDNO) FROM po WHERE po.ORDNO = t.INSHIN
  )