SELECT [Warehouse] AS [WAREHOUSE]
      ,[InvoiceDate] AS [INV_DATE]
      ,[HomestoreYorN] AS [HOMESTORE]
      ,[WeekOfDate] AS [WKOF_DATE]
      ,[FiscalPeriod] AS [FISCAL_PD]
      ,[FiscalYear] AS [FISCAL_YR]
      ,[InvoiceAmount] AS [INV$_AMT]
      ,[CreditAmount] AS [CRD$_AMT]
      ,[NumberOfTrucks] AS [NUM_TRCKS]
  FROM [PowerBI_Distribution].[CRF012B]