SELECT [podordernum]
      ,[podvendornum]
      ,[poditemnum]
      ,[podwarehouse]
      ,[poditemsequence]
      ,[podqtyordered]
      ,[podstockprice]
      ,[podorderuom]
      ,[poditemdescription]
      ,[podwhselocation]
      ,[podlastmaintained]
      ,[podextendedprice]
      ,[poditemclass]
      ,[podstatuscode]
      ,[podunitofmeasure]
      ,[podpurchaseuom]
      ,[poduomconversion]
      ,[podduedate]
      ,[podcurrentprice]
      ,[podstockqty]
      ,[podoverhead]
      ,[podcubes]
      ,[podweight]
      ,[podnopriceupdate]
      ,[podIntransitQty]
      ,[usra]
      ,[dtea]
      ,[usrc]
      ,[dtec]
      ,[podAccountNum]
      ,[podEngDrawingNum]
      ,[podDockQty]
      ,[podInspectionQty]
      ,[podScrapQty]
      ,[podDeviationQty]
      ,[podUnit]
      ,[podInvNature]
      ,[podFreightNature]
      ,[podProject]
      ,[podBuyerAcceptDate]
      ,[podVendorAcceptDate]
      ,[podMfrName]
      ,[podMfrAddress]
      ,[podMfrPartyID]
      ,[podMfrLocationID]
      ,[podMID]
      ,[podMfrAddress2]
      ,[podMfrProvince]
      ,[podMfrCity]
      ,[podMfrCountry]
      ,[podMfrZip]
      ,[podReturnedQty]
      ,[podReplacementPart]
  FROM [Wholesale_ProductSourcing_AFI].[PoDetail]
where podwarehouse = '335'

select top 10 * from Wholesale_ProductSourcing_AFI.PoDetail
