from __future__ import annotations

SHEET_CODE_TO_NAME = {
    "Sheet1": "DATA",
    "Sheet2": "HJ_SN",
    "Sheet3": "Mapics_OnHand",
    "Sheet4": "rollback",
    "Sheet5": "ASYARD",
    "Sheet6": "PO",
    "Sheet7": "KNQ delared but HJ not",
    "Sheet8": "Trips",
    "Sheet9": "KNQ_OnHand",
    "Sheet10": "KNQ_4W_Import",
    "Sheet11": "KNQ_4W_Export",
    "Sheet12": "HJ_4W_Received",
    "Sheet13": "HJ_4W_Shipped",
    "Sheet14": "Previous_Data",
    "Sheet15": "Item",
    "Sheet16": "Adjusted",
    "Sheet17": "HJ_NG",
    "Sheet18": "HJ_SN_Orphaned",
    "Sheet22": "Trailer in Yard but KNQ not",
    "Sheet23": "KNQ Variances List",
    "Sheet24": "Summary",
    "Sheet25": "Setup",
    "Sheet31": "CS",
    "Sheet33": "SH001AA2",
    "Sheet36": "exception",
    "Sheet38": "EX001AA2",
    "Sheet39": "StillNotInvoiced",
    "Sheet40": "EX001AA1",
    "Sheet42": "SH001AA1",
    "Sheet47": "AS400_SA",
    "Sheet48": "HJ_2W_SA",
}

WORKFLOW_SEQUENCE = [
    "Filter_",
    "a0_ASYARD_2_SQLADD_",
    "b031_Mapics_vs_High_Jump_SQLADD_",
    "b032_mapics_sa_transaction_",
    "b033_hj_sa_done_as400_not_",
    "a0_Mapics_OnHand_",
    "a0_mapics_adjusted_",
    "a0_Pull_HJ_SN_RLH_SQLADD_",
    "a001_Pull_HJ_NG_SQLADD_",
    "a001_Pull_HJ_SN_O_SQLADD_",
    "a0_KNQ_ONHAND_SQLSERVER_",
    "a002_KNQ_4W_IMPORTED_SQLSERVER_",
    "a003_KNQ_4W_EXPORTED_SQLSERVER_",
    "a0042_HJ_4W_Received_SQLADD_",
    "a0051_HJ_4W_Shipped_SQLADD_",
    "a007_PO_",
    "a008_Trip_",
    "a009_KNQ_Declared_but_HJ_NOT_",
    "a0091_MAPICS_HJ_KNQ_VARIANCE_",
    "a010_get_item_class_",
    "a0120_Trailer_in_Yard_KNQ_not_",
    "a0121_Copy_formula_from_N_to_U_",
    "a013_Products_item_class_",
    "a014_get_previous_ver_data_",
    "a015_mark_no_variances_items_",
    "a018_CopyFilteredData_",
    "a019_CopyFilteredData_SH001AA1_",
    "a020_CopyFilteredData_NG001VD3_",
    "a020_1CopyFilteredData_EX001AA2_",
    "a020_CopyFilteredData_SH001AA2_",
    "a021_CN001AA1_",
    "a022_EX001AA2_",
    "b01_add_orphaned_column_",
    "b02_DATA_VARIANCE_",
    "b05_product_",
    "B06_sh001aa2_to_sheet1_",
    "Filter_",
]
