WITH oh1 AS 
(SELECT a1.ITNBR,t2.ITDSC,t2.ITCLS,a1.HOUSE,SUM(a1.LQNTY) AS ONHAND 
FROM Manufacturing_ProductionPlanning_MIL.SLQNTY AS a1 
LEFT JOIN (SELECT a.ITNBR, a.ITCLS, a.ITDSC FROM MasterData_ItemMaster_MIL.ITMRVA AS a WHERE a.STID IN ('51')) AS t2 on a1.itnbr = t2.itnbr 
WHERE a1.HOUSE IN ('51') AND a1.LLOCN NOT IN ('RS001','S01ST1','PIC01','LMF001') 
GROUP BY a1.ITNBR,t2.ITDSC,t2.ITCLS,a1.HOUSE 
) 

-- final table for "Weighted_Avg_Inventory_Age(Days)"
SELECT g.HOUSE, g.ITNBR, g.ONHAND, CAST((SUM(g.Item_Inventory_Age_Days*g.ALC_QTY)/g.ONHAND) AS DECIMAL(10,2)) AS "Weighted_Avg_Inventory_Age(Days)"  
FROM 
(
SELECT t0.HOUSE, t0.ITNBR, t0.UPDDT, t0.TRX_QTY, t0.ACC_QTY, t0.ONHAND, t0.ONHAND-t0.ACC_QTY AS Balance,
-- get item inventory age by item and inbound date
(CASE 
        WHEN t0.ONHAND >= t0.ACC_QTY 
            AND CAST(GETDATE() AS DATE) = CAST(CONCAT('20', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 2, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 4, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 6, 2)) AS DATE) 
            THEN 1 
        WHEN t0.ONHAND >= t0.ACC_QTY 
            AND CAST(GETDATE() AS DATE) > CAST(CONCAT('20', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 2, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 4, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 6, 2)) AS DATE) 
            THEN DATEDIFF(DAY, CAST(CONCAT('20', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 2, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 4, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 6, 2)) AS DATE), CAST(GETDATE() AS DATE)) 
        WHEN t0.ONHAND < t0.ACC_QTY 
            AND ABS(t0.ONHAND - t0.ACC_QTY) < t0.TRX_QTY 
            AND CAST(GETDATE() AS DATE) = CAST(CONCAT('20', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 2, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 4, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 6, 2)) AS DATE) 
            THEN 1 
        WHEN t0.ONHAND < t0.ACC_QTY 
            AND ABS(t0.ONHAND - t0.ACC_QTY) < t0.TRX_QTY 
            AND CAST(GETDATE() AS DATE) > CAST(CONCAT('20', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 2, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 4, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 6, 2)) AS DATE) 
            THEN DATEDIFF(DAY, CAST(CONCAT('20', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 2, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 4, 2), '-', SUBSTRING(CAST(t0.UPDDT AS VARCHAR(8)), 6, 2)) AS DATE), CAST(GETDATE() AS DATE)) 
        WHEN t0.ONHAND < t0.ACC_QTY 
            AND ABS(t0.ONHAND - t0.ACC_QTY) >= t0.TRX_QTY 
            THEN 0 
        ELSE 0 
    END) AS Item_Inventory_Age_Days,

-- get allocated qty
(CASE 
    WHEN t0.ONHAND >= t0.ACC_QTY THEN t0.TRX_QTY
    WHEN t0.ONHAND-t0.ACC_QTY<0 AND ABS(t0.ONHAND-t0.ACC_QTY) < t0.TRX_QTY THEN T0.TRX_QTY - ABS(t0.ONHAND-t0.ACC_QTY)
    WHEN t0.ONHAND-t0.ACC_QTY<0 AND ABS(t0.ONHAND-t0.ACC_QTY) >= t0.TRX_QTY THEN 0 ELSE 0 END ) AS ALC_QTY

FROM
-- get inbound acccumulated qty
(
SELECT a.HOUSE, a.ITNBR, a.UPDDT, a.TRX_QTY, SUM(a.TRX_QTY) OVER (PARTITION BY a.ITNBR ORDER BY a.UPDDT DESC) AS ACC_QTY, oh1.ONHAND 
FROM 
(SELECT T1.HOUSE, T1.ITNBR, T1.UPDDT, SUM(T1.TRQTY) as TRX_QTY 
FROM Manufacturing_Inventory_MIL.IMHIST AS T1
WHERE T1.HOUSE='51' AND EXISTS ( SELECT 1 FROM (SELECT i.ITNBR FROM Manufacturing_ProductionPlanning_MIL.SLQNTY  AS i WHERE i.LQNTY <> 0 AND i.HOUSE IN ('51') AND i.LLOCN NOT IN ('RS001','S01ST1','PIC01','LMF001') GROUP BY i.ITNBR) AS b1 WHERE b1.ITNBR = T1.ITNBR)      
AND T1.UPDDT BETWEEN '1'+ SUBSTRING(CONVERT(VARCHAR(8), GETDATE() - 720, 112),3,6) AND '1'+SUBSTRING(CONVERT(VARCHAR(8), GETDATE(), 112),3,6)   
AND T1.TRQTY<>0 AND T1.TCODE IN ('RP','RI','RM','RS') 
GROUP BY T1.ITNBR, T1.HOUSE, T1.UPDDT
) AS a, oh1 WHERE a.ITNBR = oh1.ITNBR) AS t0 
WHERE (CASE 
    WHEN t0.ONHAND >= t0.ACC_QTY THEN t0.TRX_QTY
    WHEN t0.ONHAND-t0.ACC_QTY<0 AND ABS(t0.ONHAND-t0.ACC_QTY) < t0.TRX_QTY THEN T0.TRX_QTY-ABS(t0.ONHAND-t0.ACC_QTY)
    WHEN t0.ONHAND-t0.ACC_QTY<0 AND ABS(t0.ONHAND-t0.ACC_QTY) >= t0.TRX_QTY THEN 0 ELSE 0 END ) >0
--ORDER BY t0.ITNBR, t0.UPDDT DESC
) AS g 
GROUP BY g.HOUSE, g.ITNBR, g.ONHAND