/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [Trip#]
        ,right('0000000'+ cast(trim(cast([Trip#] as VARCHAR(10))) as VARCHAR(6)), 7) as [Trip#1]
      ,[TripStatus]
      ,[Container]
      ,[ContainerID]
      ,[Container#]
      ,[Door#]
      ,[PiecesRouted]
      ,[Drops]
      ,[Cubes]
      ,[Cubes Loaded]
      ,[TotScanSer#]
      ,[TotScanNoTag]
      ,[TripType]
      ,[% Complete]
      ,[PiecesLoaded]
      ,[PiecesRemaining]
      ,[Carrier]
      ,[LatestDeliverDate]
      ,[STATE1]
      ,[STATE2]
      ,[STATE3]
      ,[TripCreateDate]
      ,[TripCreateTime]
      ,[TrailerType]
      ,[Warehouse]
      ,[Region]
      ,a.[DispatchDatetime]
      ,[Now]
      ,[TimeDiff in Hrs]
      ,a.[DispatchDate]
      ,[DispatchDay]
      ,[TimeSlot]
      ,[Dispatch Time]
      ,[Created Date]
      ,[Created Time]
	  ,b.[actual_ship_date]
      ,b.[actual_delivery_date]
	  
  FROM [PowerBI_Distribution].[Transportation_TruckLoads] a 
  LEFT JOIN [PowerBI_Distribution].[loadpassdispatch] b
  ON right('0000000'+ cast(trim(cast(a.[Trip#] as VARCHAR(10))) as VARCHAR(6)), 7)=substring(b.load_id,1,7)
  and a.Warehouse=b.wh_id
