SELECT
    t4.ITNBR,
    t4.STID,
    t2.MOHTQ,
    t2.PLREQ as Demand,
    t2.DOFLS as date_of_last_sales,
    t2.LDQOH as Last_date_affecting_onhand,
    t2.WHSLC,
    t2.ITCLS,
    t4.B2Z95S AS UnitCube,
    t4.ITDSC,
    t1.TIHIUNLD,
    t1.PICKPUT,
    t1.ITMCLSID,
    t1.UNITSWIDE,
    t1.UNITLAYERS,
    t1.UNITSDEEP,
    t1.SCOOPQTY,
    t1.SKIDSIZE,
    t3.QTYCR,
    t3.NBSEAT,
    t3.CRTWIN,
    t3.CRTLIN,
    t3.CRTHIN,
    t3.PRDWIN,
    t3.PRDHIN,
    t3.PRDLIN,
    t3.ITMWEGHT,
    CAST(t3.ITMWEGHT * 0.453592 AS DECIMAL(10,2)) AS "Unit_Weight(KG)",
    t2.MPUPQ AS OPEN_PO,
    CASE
        WHEN t2.MOHTQ / NULLIF(t1.SCOOPQTY, 0) <= 1 THEN 1
        ELSE ROUND(t2.MOHTQ / NULLIF(t1.SCOOPQTY, 0))
    END AS PALLETS,
    CAST(t1.SCOOPQTY * t3.ITMWEGHT * 0.453592 AS DECIMAL(10,2)) AS "SCOOP_Weight(KG)"
FROM (SELECT * FROM AMFLIBA.ITMRVA t WHERE t.STID = '335' ) AS t4
LEFT JOIN (SELECT * FROM AMFLIBA.ITEMBL a0 where a0.HOUSE = '335') AS t2 ON t4.ITNBR = t2.ITNBR AND t4.STID = t2.HOUSE
LEFT JOIN AFILELIB.ITBEXT t1 ON t1.ITNBR = t4.ITNBR AND t1.HOUSE = t4.STID
LEFT JOIN AFILELIB.ITMEXT t3 ON t3.ITNBR = t4.ITNBR
WHERE t4.STID = '335'
--   AND (t2.MOHTQ > 0 or   t2.MPUPQ>0 or t2.PLREQ>0 )