let
    Source = Odbc.Query("dsn=AFIPROD", 
    " SELECT a.ITNBR,a.HOUSE, a.ITCLS, (CURRENT_DATE ) AS ""DATE"", a.MOHTQ, a.WHSLC, a.ITDSC,
    (CASE 
    WHEN a.ITCLS NOT LIKE 'Z%' THEN 'RP'
    WHEN SUBSTR(a.ITNBR,1,4)='100-' THEN 'CG'
    WHEN SUBSTR(a.ITNBR,1,1) in ('A','B','D','E','H','L','P','Q','M','R','T','W','Z') THEN 'CG'
    ELSE 'UPH' END) as Product
    FROM 
    (SELECT T1.ITNBR,T1.HOUSE, T1.ITCLS, T1.MOHTQ, T1.WHSLC, T2.ITDSC    
    FROM AMFLIBA.ITEMBL T1, AMFLIBA.ITMRVA T2, AMFLIBA.WHSMST T3 
    WHERE  T2.ITCLS = T1.ITCLS AND T2.ITNBR = T1.ITNBR AND T2.STID = T3.STID AND T1.HOUSE = T3.WHID AND (T1.HOUSE='335' AND T1.MOHTQ<>0)
    ORDER BY T1.ITNBR) as a ")
in
    Source