let
    Source = Odbc.Query(
    "dsn=AFIPROD", 
    "-- 使用CTE和LEFT JOIN优化查询 -- Oct.02.2024 by Jim,Shen#(lf)
    WITH BOX_ID AS    
(SELECT T1.BXDSTID,T1.BXDPARENTITEMNUMBER,T1.BXDCOMPONENTITEMNUMBER, T1.BXDCOMPONENTITEMDESCRIPTION    
FROM RGNFILL.PSTBOMD T1    
Where T1.BXDSTID IN ('51') AND TRIM(T1.BXDPARENTITEMNUMBER) LIKE '%UN' AND     
(CASE WHEN T1.BXDCOMPONENTITEMDESCRIPTION LIKE 'RSC%' THEN 1     
WHEN T1.BXDUNITVOLUME >0 THEN 1     
WHEN T1.BXDCOMPONENTITEMDESCRIPTION LIKE 'UWALL%' THEN 1     
WHEN T1.BXDCOMPONENTITEMDESCRIPTION LIKE '%X%X%INCH%' THEN 1    
ELSE 0 END)=1)    
SELECT t1.ITNBR,t3.MOHTQ, t3.WHSLC, t1.STID, t1.ITCLS, t1.B2Z95S as Cubes,     
t1.ITDSC, t1.WEGHT,t2.ITMCQTY,    
(CASE     
WHEN t1.ITCLS like 'TAF%' THEN 'RP'    
WHEN t1.ITCLS IN ('MTA','CTA','FFR','MVN') THEN 'RP'    
WHEN t1.ITCLS IN ('PACS','ZACM','WVVG') THEN 'UnKits'    
WHEN t1.ITCLS LIKE 'Z%K' THEN 'UnKits'    
WHEN t1.ITCLS IN ('ZDTP','ZKBP') THEN 'Pillow'    
WHEN t1.ITCLS IN ('ZASU','ZMLH','ZMLR','ZUSR','ZUSU','ZVUC','ZXUC','ZUSU','ZUMU','ZAMU','ZASM','ZASR','ZDMA','ZMUC','ZSUS','ZUMS','ZUSM','ZVMA','ZVUS','ZXLH','ZXLM','ZXLR','ZXMS','ZXMU') THEN 'UPH'    
WHEN t1.ITCLS IN ('ZDAA','ZDAE','ZDWC','ZDAY','ZVAA','ZDAB','ZDAW','ZDYB','ZDBC','ZABC','ZECD') THEN 'CG'    
WHEN t1.ITCLS IN ('ZBMA','ZKIS','ZAIS','ZKBA','ZNFR','ZKBP','ZNFR') THEN 'Bedding'     
WHEN t1.ITCLS IN ('WPLS') THEN 'Plastics'    
WHEN t1.ITCLS IN ('WVBC','WVCS') THEN 'Foundation'     
WHEN t1.ITCLS IN ('PANL') THEN 'Panel'    
WHEN t1.ITCLS IN ('ZKIZ') THEN 'ZipperCover'    
WHEN t1.ITCLS IN ('BBFR','WVHC') THEN 'Verona'     
WHEN t1.ITCLS NOT LIKE 'Z%' THEN 'RawMaterial'     
ELSE 'Check' END) AS Product,    
t4.BXDCOMPONENTITEMNUMBER as BOX_MRP,     
t4.BXDCOMPONENTITEMDESCRIPTION as BOX_DES    
FROM AMFLIBL.ITMRVA t1    
LEFT JOIN (SELECT a.ITNBR,a.ITMCQTY FROM AFILELIBL.ITMEXT AS a) AS t2 ON t2.ITNBR = t1.ITNBR    
LEFT JOIN (SELECT b.ITNBR, b.MOHTQ, b.HOUSE, b.WHSLC FROM AMFLIBL.ITEMBL AS b WHERE b.HOUSE IN ('51')) AS t3 ON t3.ITNBR = t1.ITNBR    
LEFT JOIN BOX_ID AS t4 ON t1.STID = t4.BXDSTID AND TRIM(t1.ITNBR)= TRIM(t4.BXDPARENTITEMNUMBER)    
WHERE t1.STID='51'    
ORDER BY t1.ITNBR    

    
    "),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"XCUS#", type text}, {"ITCSNO", type text}, {"INIVDT", type text}, {"XNINVR", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"CUSNM", "CustomerName"}})
in
    #"Renamed Columns"