SELECT
    t4.INWHSE,
    t4.INIVDT,
    t1.CUSNM,
    t4.INIVDT || '_' || CHAR(t5.XNTRPN) AS Container#,
    CHAR(t5.XNTRPN) AS TRIP#,
    t6.ITITNO,
    t6.ITITCL,
    t6.ITSHQT,
    CASE
        WHEN t6.ITITNO LIKE '100-%' THEN 'CG'
        WHEN t6.ITITCL NOT LIKE 'Z%' THEN 'RP'
        WHEN SUBSTR(t6.ITITNO, 1, 1) IN ('1','2','3','4','5','6','7','8','9','U') THEN 'UPH'
        ELSE 'CG'
    END AS Product,
    (t2.CUBES * t6.ITSHQT) AS CUBES,
    t2.UUCCIM,
    t7.XCUS#,
    t6.ITSPNO,
    t5.XNINVR,
    t5.XNORNO,
    t4.INPONO
FROM AFILELIB.TSININA1 t4
JOIN AFILELIB.TSITXN t7
    ON t4.INORNO = t7.XTORNO AND t4.ININVR = t7.XTINVR
JOIN AFILELIB.TSITIN t6
    ON t7.XTORNO = t6.ITORNO
    AND t7.XTINVR = t6.ITINVR
    AND t7.XTITNO = t6.ITITNO
    AND t7.XTITSQ = t6.ITITSQ
    AND t7.XRIDAT = t6.ITRIDT
JOIN AFILELIB.TSINXN t5
    ON t6.ITORNO = t5.XNORNO
    AND t6.ITINVR = t5.XNINVR
JOIN AFILELIB.ACUSMASJ t1
    ON t6.ITCSNO = t1.CUSNO
JOIN AMFLIBA.MBBZRES1 t3
    ON t6.ITITNO = t3.BZAITX
JOIN AFILELIB.ITMEXT t2
    ON t3.BZAITX = t2.ITNBR
WHERE
    t4.INWHSE = '335'
    AND t4.INWHSE = t6.ITWHSE
    AND t6.ITCSNO = t7.XCUS#
    AND t7.XCUS# = t4.INCSNO
    AND t5.XNTRPN <> 0
    AND t4.INIVDT BETWEEN 20250722 AND 20250723
    AND t6.ITSHQT > 0
ORDER BY
    t4.INIVDT,
    t5.XNTRPN
