;WITH Nhap AS (
    SELECT
        P.DPHIEUID,
        H.DPHIEU_HANGID,
        P.DHOPDONGID,
        P.MA_KNQ,
        P.SOTK,
        P.NGAY_DK,
        P.SO_PHIEU,
        P.NGAY_PHIEU,
        P.SO_HD,
        P.NGAY_HD,
        P.MA_NT,
        H.STTHANG,
        H.MA_SP,
        H.TEN_SP,
        H.DINH_DANH_HANG_HOA,
        H.MA_NUOC,
        H.MA_HS,
        H.MA_DVT,
        H.SO_LUONG,
        H.DON_GIA,
        H.GHI_CHU,
        NKEY.SOTK_KEY,
        NKEY.SO_PHIEU_KEY,
        ISNULL(H.STTHANG, 0) AS STTHANG_KEY
    FROM ECUS5_KNQ.dbo.DPHIEU P
    INNER JOIN ECUS5_KNQ.dbo.DPHIEU_HANG H
        ON P.DPHIEUID = H.DPHIEUID
    CROSS APPLY (
        SELECT
            NULLIF(LTRIM(RTRIM(REPLACE(CAST(P.SOTK AS VARCHAR(50)), '.0', ''))), '') AS SOTK_KEY,
            NULLIF(LTRIM(RTRIM(P.SO_PHIEU)), '') AS SO_PHIEU_KEY
    ) NKEY
    WHERE
        P._XORN = 'N'
        AND P.MA_KNQ = 'VNNSL'
        AND ISNULL(P.HUY_TRANG_THAI, 0) = 0
        AND ISNULL(H.IS_HUY, 0) = 0
        AND ISNULL(H.IS_XUAT, 0) = 0
        AND ISNULL(H.IS_KETTHUC_GETIN, 0) = 1
        AND ISNULL(P.TRANG_THAI, '') NOT IN ('T', '0', '1', 'H')
        AND (P.MESSAGEID IS NOT NULL OR P.NGAY_DK IS NOT NULL OR P.SO_PHIEU LIKE '%RH%')
        AND NKEY.SOTK_KEY LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
),
Xuat AS (
    SELECT
        HX.MA_SP,
        ISNULL(HX.STTHANG_N, 0) AS STTHANG_N_KEY,
        ISNULL(HX.SO_LUONG, 0) AS SO_LUONG_XUAT,
        PX.NGAY_XUAT,
        XKEY.SOTK_N_KEY,
        XKEY.SO_PHIEU_N_KEY
    FROM ECUS5_KNQ.dbo.DPHIEU PX
    INNER JOIN ECUS5_KNQ.dbo.DPHIEU_HANG HX
        ON PX.DPHIEUID = HX.DPHIEUID
    CROSS APPLY (
        SELECT
            NULLIF(LTRIM(RTRIM(REPLACE(CAST(HX.SOTK_N AS VARCHAR(50)), '.0', ''))), '') AS SOTK_N_KEY,
            NULLIF(LTRIM(RTRIM(HX.SO_PHIEU_N)), '') AS SO_PHIEU_N_KEY
    ) XKEY
    WHERE
        PX._XORN = 'X'
        AND PX.MA_KNQ = 'VNNSL'
        AND ISNULL(PX.HUY_TRANG_THAI, 0) = 0
        AND ISNULL(HX.IS_HUY, 0) = 0
        AND (PX.MESSAGEID IS NOT NULL OR PX.NGAY_DK IS NOT NULL OR PX.NGAY_XUAT IS NOT NULL)
),
XuatTheoNhap AS (
    SELECT
        N.DPHIEU_HANGID,
        SUM(X.SO_LUONG_XUAT) AS LUONG_XUAT,
        MAX(X.NGAY_XUAT) AS NGAY_XUAT_CUOI
    FROM Nhap N
    INNER JOIN Xuat X
        ON X.MA_SP = N.MA_SP
       AND X.STTHANG_N_KEY = N.STTHANG_KEY
       AND (
            X.SOTK_N_KEY = N.SOTK_KEY
            OR X.SO_PHIEU_N_KEY = N.SO_PHIEU_KEY
       )
    GROUP BY N.DPHIEU_HANGID
)
SELECT
    ROW_NUMBER() OVER (ORDER BY N.NGAY_PHIEU DESC, N.SOTK_KEY, N.STTHANG) AS N'STT',
    N.SOTK_KEY AS N'Số TK nhập',
    CONVERT(VARCHAR(10), N.NGAY_DK, 103) AS N'Ngày TK',
    N.SO_PHIEU AS N'Số PNK',
    CONVERT(VARCHAR(10), N.NGAY_PHIEU, 103) AS N'Ngày NK',
    N.SO_HD AS N'Số hợp đồng',
    CONVERT(VARCHAR(10), N.NGAY_HD, 103) AS N'Ngày hợp đồng',
    N.MA_SP AS N'Mã hàng',
    N.TEN_SP AS N'Tên hàng',
    ISNULL(
        NULLIF(LTRIM(RTRIM(N.DINH_DANH_HANG_HOA)), ''),
        RIGHT(CAST(YEAR(ISNULL(N.NGAY_DK, N.NGAY_PHIEU)) AS VARCHAR(4)), 2)
        + N.SOTK_KEY
        + '-'
        + RIGHT('00' + CAST(ISNULL(N.STTHANG, 1) AS VARCHAR(10)), 2)
    ) AS N'Định danh hàng hóa',
    M.MA_NUOC AS N'Xuất xứ',
    M.MA_HS AS N'Mã HS',
    N.SO_LUONG AS N'Lượng',
    M.DON_GIA AS N'Đơn giá',
    M.MA_DVT AS N'Đơn vị tính',
    ISNULL(X.LUONG_XUAT, 0) AS N'Lượng xuất',
    ROUND(N.SO_LUONG - ISNULL(X.LUONG_XUAT, 0), 3) AS N'SL Tồn',
    ROUND((N.SO_LUONG - ISNULL(X.LUONG_XUAT, 0)) * M.DON_GIA, 2) AS N'Trị Giá Tồn',
    N.MA_NT AS N'Mã NT',
    CONVERT(VARCHAR(10), N.NGAY_PHIEU, 103) AS N'Ngày nhập',
    CONVERT(VARCHAR(10), X.NGAY_XUAT_CUOI, 103) AS N'Ngày xuất',
    DATEDIFF(day, N.NGAY_PHIEU, GETDATE()) AS N'Số ngày tồn',
    N.GHI_CHU AS N'Ghi chú'
FROM Nhap N
LEFT JOIN XuatTheoNhap X
    ON X.DPHIEU_HANGID = N.DPHIEU_HANGID
OUTER APPLY (
    SELECT TOP 1
        COALESCE(NULLIF(N.MA_NUOC, ''), NULLIF(HD.MA_NUOC, ''), NULLIF(SP.MA_NUOC, ''), 'VN') AS MA_NUOC,
        COALESCE(NULLIF(N.MA_HS, ''), NULLIF(HD.MA_HS, ''), NULLIF(SP.MA_HS, '')) AS MA_HS,
        COALESCE(NULLIF(N.MA_DVT, ''), NULLIF(HD.MA_DVT, ''), NULLIF(SP.MA_DVT, '')) AS MA_DVT,
        COALESCE(N.DON_GIA, HD.DON_GIA, 0) AS DON_GIA
    FROM (SELECT 1 AS DUMMY_ROW) D
    LEFT JOIN ECUS5_KNQ.dbo.DHOPDONG_HANG HD
        ON N.DHOPDONGID = HD.DHOPDONGID
       AND N.MA_SP = HD.MA_SP
    LEFT JOIN ECUS5_KNQ.dbo.SSANPHAM SP
        ON N.MA_SP = SP.MA_SP
       AND SP.MA_KNQ = N.MA_KNQ
    ORDER BY HD.DHOPDONG_HANGID
) M
WHERE
    ROUND(N.SO_LUONG - ISNULL(X.LUONG_XUAT, 0), 3) > 0.001
ORDER BY
    N.NGAY_PHIEU DESC,
    N.SOTK_KEY,
    N.STTHANG;