Select SYSTEM_TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, varchar(COLUMN_TEXT, 50) As COLUMN_DESC 
From QSYS2.SYSCOLUMNS
Where TABLE_NAME in ('BTTRIPD','BTTRIPH','ITEMBL','ITMRVA','ITMEXT','ITMFPR','ITMPRB','PRICE','UAG3CPP','SETDETL','SETHEDR','SetAppl','PSTRUC','TBL_TRIPLESS_ITEM_DETAILS','LOGFCST',
'IMHIST','ATPSUM','CODATAN','SCP_FCST_ROOT','ATPSUP','TAGINVD','TAGINVD2','AINVCTL','INSTAT','INEXCD','COMAST','CODATAN','EXTORD',
'ACUSMASJ','AEXTCUS','VENNAML0','ITMEXT','ITEMASA','SetAppl','WHFILRQ')