SELECT 
      [Date_ID] AS [DateID]
      ,[Fiscal_Day_Of_Week_Name]
      ,[First_Date_Of_Fiscal_Week]
      ,[Last_Date_Of_Fiscal_Week] AS [Week Ending Date]
      ,[Fiscal_Month]
      ,[Fiscal_Month_Number]
      ,[Fiscal_Quarter_Number]
      ,[Fiscal_Year]
      ,[Fiscal_Week_Of_Year]
      ,[Last_Date_Of_Fiscal_Year]
      ,[Fiscal_Year_Diff]
      ,[Fiscal_Week_Diff]
      ,[Fiscal_Day_Diff]
      ,[Yesterday_Flag]
      ,[Fiscal_WTD_Flag]
      ,[Fiscal_MTD_Flag]
      ,[Fiscal_YTD_Flag]
      ,[First_Date_Of_Fiscal_Year]
  FROM [PowerBI_Enterprise].[DimDate]
  where cast([date_id]as date) BETWEEN DATEADD(day,-45,GETDATE()) AND GETDATE()