WITH X AS (
    SELECT T1.TCODE, T1.ITNBR, T1.HOUSE, T2.ITCLS, T1.TRQTY,
    DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2)) AS DATE,
    WEEK(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS WEEK,
    YEAR(DATE('20'||SUBSTR(CHAR(T1.UPDDT),2,2)||'-'||SUBSTR(CHAR(T1.UPDDT),4,2)||'-'||SUBSTR(CHAR(T1.UPDDT),6,2))) AS YEAR
    FROM AMFLIBL.IMHIST T1
    JOIN AMFLIBL.ITMRVA T2 ON T2.ITNBR = T1.ITNBR
    JOIN AMFLIBL.WHSMST T3 ON T3.STID = T2.STID AND T1.HOUSE = T3.WHID
    WHERE T1.HOUSE = '51'
    AND T1.UPDDT BETWEEN CHAR('1'||VARCHAR_FORMAT(current date - 31 days,'YYMMDD')) AND CHAR('1'||VARCHAR_FORMAT(current date,'YYMMDD'))
    AND T1.TRQTY <> 0
    AND T1.TCODE IN ('RP','PQ','RM','RS','RC','IA','LA','SA','IP','IS','VR','IU','SC','SM','SP','SS')
    ORDER BY T1.ITNBR
),
Y AS (
    SELECT b1.RPAITX AS PITEM, MAX(b1.RPAMVA) as PAMNT
    FROM (
        SELECT x.RPAITX, x.ITCLS, x.RPAMVA, x.RPBLDT, x.RPZ0D7
        FROM (
            (
                (SELECT a.RPAITX, (CASE WHEN a.RPBRCD IN ('VND') THEN a.RPAMVA/23090 ELSE a.RPAMVA END) AS RPAMVA, a.RPBLDT, a.RPZ0D7, T2.ITCLS
                FROM AMFLIBL.ITMFPR a
                LEFT JOIN AMFLIBL.ITMRVA T2 ON a.RPAITX = T2.ITNBR AND a.RPZ0D7 = T2.STID
                WHERE a.RPZ0D7 = '51'
                AND a.RPAITX || a.RPZ0D7 || a.RPBLDT IN (
                    SELECT a.RPAITX || a.RPZ0D7 || MAX(a.RPBLDT) RPBLDT
                    FROM AMFLIBL.ITMFPR a
                    WHERE a.RPZ0D7 = '51'
                    GROUP BY a.RPAITX, a.RPZ0D7
                ))
                UNION ALL
                (SELECT t1.ITNO1G, t1.UCCT1G/23090 AS RPAMVA, t1.CCDT1G, t1.STID1G, t1.STID1G
                FROM AMFLIBL.ITMPRB t1)
            )
            UNION ALL
            (SELECT t1.ITNBR, t1.LCOST/23090 AS RPAMVA, t1.LDQOH, t1.HOUSE, t1.ITCLS
            FROM AMFLIBL.ITEMBL t1)
        ) AS x
        ORDER BY x.RPAITX, x.RPAMVA ASC
    ) b1
    GROUP BY b1.RPAITX
)
SELECT X.ITNBR, X.HOUSE, X.ITCLS, X.DATE, X.WEEK, X.YEAR, X.YEAR * 100 + X.WEEK AS "YearWeek", X.TRQTY, Y.PAMNT AS "UP($USD)",
        (CASE WHEN X.ITCLS IN ('WPLS','PLST') THEN 'PLASTIC'   
            WHEN X.ITCLS IN ('PVN2','QA','QB') THEN 'RAW'  
            WHEN X.ITCLS LIKE 'CH%' THEN 'RAW'  
            WHEN X.ITCLS LIKE 'CR%' THEN 'RAW'              
            WHEN X.ITCLS IN ('TAF') THEN 'RP' 
            WHEN X.ITCLS IN ('CTA','MTA','HTA') THEN 'RP CGs' 
            WHEN X.ITCLS IN ('FFR') THEN 'FFR'   
            WHEN X.ITCLS IN ('BBFR') THEN 'FR SOCK'   
            WHEN X.ITCLS IN ('ZDTP') THEN 'PILLOW'   
            WHEN X.ITCLS IN ('MVN') THEN 'QUILTING'   
            WHEN X.ITCLS IN ('ZKIZ') THEN 'ZIPPER COVER'   
            WHEN X.ITCLS IN ('WVHC','WVVG') THEN 'VERONA'    
            WHEN X.ITCLS IN ('PVN') THEN 'FABRIC'   
            WHEN X.ITCLS IN ('WVCS') THEN 'FOUNDATION'   
            WHEN X.ITCLS IN ('ZABC','ZECD','ZDAA','ZECD','ZDWC','ZDAB','ZDAE','ZDAW','ZDBC','ZDWC','ZDAY','ZEBR','ZVTY') THEN 'CASEGOODS'   
            WHEN X.ITCLS IN ('ZAIS','ZKIS','ZNFR','ZKBP','ZKBA','ZBMA','TAB') THEN 'BEDDING'   
            WHEN X.ITCLS LIKE  'Z%K' THEN 'UNKITS'   
            ELSE 'Check' END) AS Product, 
(CASE
        WHEN X.TCODE IN ('RP','RI','RM','RS','RC','IA','LA') THEN 'IN'
        WHEN X.TCODE IN ('SA','IP','IS','VR','IU','SC','SM','SP','SS') THEN 'OUT'
        ELSE 'CHECK'
    END) AS "TYPE",
(CASE
        WHEN Y.PAMNT IS NULL AND X.ITCLS NOT LIKE 'Z%' THEN 0
        WHEN Y.PAMNT IS NULL AND X.ITCLS LIKE 'Z%' THEN DECIMAL(X.TRQTY) * 50
        ELSE DECIMAL(X.TRQTY) * COALESCE(Y.PAMNT,0)
    END) AS "AMT($USD)"
FROM X
LEFT JOIN Y ON X.ITNBR = Y.PITEM