SELECT [Date_Key]
      ,[Mapics_Date]
      ,[Date_ID] AS [DateID]
      ,[DateTime_ID]
      ,[Calendar_Date]
      ,[Calendar_Day_Of_Week_Name]
      ,[Calendar_Day_Of_Week]
      ,[Calendar_Week_Number_As_Integer]
      ,[Last_Date_Of_Calendar_Week] AS [CalendarWeekLastDate]
      ,[Calendar_Year_Month_As_Integer]
      ,[Calendar_Day_Of_Month]
      ,[Calendar_Week_Of_Month]
      ,[Calendar_Quarter_Number]
      ,[Calendar_Year]
      ,[Calendar_Day_Of_Year]
      ,[Calendar_Week_Of_Year]
      ,[Fiscal_Date]
      ,[Fiscal_Day_Of_Week_Name]
      ,[Fiscal_Day_Of_Week]
      ,[Fiscal_Week_Number_As_Integer]
      ,[First_Date_Of_Fiscal_Week]
      ,[Last_Date_Of_Fiscal_Week]
      ,[Fiscal_Month]
      ,[Fiscal_Month_Number]
      ,[Fiscal_Day_Of_Month]
      ,[Fiscal_Week_Of_Month]
      ,[Fiscal_Quarter_Number]
      ,[Fiscal_Year]
      ,[Fiscal_Day_Of_Year]
      ,[Fiscal_Week_Of_Year]
      ,[Last_Date_Of_Fiscal_Year]
      ,[Holiday_Indicator]
      ,[Holiday_Name]
      ,[Working_Day_Indicator]
      ,[Weekday_Weekend]
      ,[Fiscal_Year_Diff]
      ,[Fiscal_Quarter_Diff]
      ,[Fiscal_Month_Diff]
      ,[Fiscal_Week_Diff]
      ,[Fiscal_Day_Diff]
      ,[Calendar_Year_Diff]
      ,[Calendar_Quarter_Diff]
      ,[Calendar_Month_Diff]
      ,[Yesterday_Flag]
      ,[Fiscal_WTD_Flag]
      ,[Fiscal_MTD_Flag]
      ,[Fiscal_YTD_Flag]
      ,[First_Day_Of_Calendar_Month_Indicator]
      ,[First_Day_Of_Fiscal_Month_Indicator]
      ,[Last_Day_Of_Calendar_Month_Indicator]
      ,[Last_Day_Of_Fiscal_Month_Indicator]
      ,[First_Date_Of_Fiscal_Year]
  FROM [PowerBI_Enterprise].[DimDate]
  where [date_id] BETWEEN DATEADD(DAY,-15,GETDATE()) AND GETDATE()