/* 查看已全部出库完毕、满足清算/结关条件的保税仓合同列表 */


-- STEP 1: 找出当前未结关、未作废的有效保税仓合同
SELECT A.MA_KNQ, A.DHOPDONGID, A.SO_HD, A.NGAY_NHAP, A.NGAY_KY, A.NGAY_HH, 
       A.IS_THANH_LY, A.IS_HUY, A.TRANG_THAI, A.MA_KH, B.TEN_KH, 
       CAST(0 AS FLOAT) AS SO_LUONG_GETIN, 
       CAST(0 AS FLOAT) AS SO_LUONG_GETOUT, 
       CAST(0 AS FLOAT) AS SO_LUONG_TON
INTO #DHOPDONG 
FROM DHOPDONG A 
LEFT JOIN SKHACHHANG B ON A.MA_KNQ = B.MA_KNQ AND A.MA_KH = B.MA_KH 
LEFT JOIN DTHONGBAO C ON A.DHOPDONGID = C.DHOPDONGID
WHERE A.MA_KNQ = '你的保税仓代码' 
  AND ISNULL(A.IS_THANH_LY, 0) = 0   -- 过滤：未清算/未完成的合同
  AND A.TRANG_THAI <= 3              -- 过滤：状态小于等于3的合同
  AND ISNULL(A.IS_HUY, 0) = 0;       -- 过滤：未作废的合同

-- STEP 2: 从出入库单证（DPHIEU）中汇总所有进出口数量
SELECT A.MA_KNQ, A.DHOPDONGID, 
       CAST(SUM(SO_LUONG) AS NUMERIC(20,4)) AS SO_LUONG, 
       CAST(SUM(SO_LUONG_GETOUT) AS NUMERIC(20,4)) AS SO_LUONG_GETOUT, 
       SO_HD 
INTO #DPHIEU 
FROM ( 
    -- 1) 类型为 2 (散货/普通货物) 的入库数量 (_XORN = 'N')
    SELECT B.MA_KNQ, C.MA_KH, A.DINH_DANH_HANG_HOA, B.DHOPDONGID, B.SO_PHIEU, B.NGAY_PHIEU, 
           (A.SO_LUONG) AS SO_LUONG, CAST(NULL AS VARCHAR) AS SO_PHIEU_XUAT, 
           CAST(NULL AS DATETIME) AS NGAY_PHIEU_XUAT, CAST(NULL AS FLOAT) AS SO_LUONG_GETOUT
    FROM DPHIEU_HANG A 
    INNER JOIN DPHIEU B ON A.DPHIEUID = B.DPHIEUID 
    INNER JOIN DHOPDONG C ON B.DHOPDONGID = C.DHOPDONGID 
    WHERE B.MA_KNQ = '你的保税仓代码' AND B._XORN = 'N' AND B.TRANG_THAI = 'T' 
      AND ISNULL(A.IS_HUY, 0) = 0 AND B.TYPE = 2 
      AND B.DHOPDONGID IN (SELECT DHOPDONGID FROM #DHOPDONG)

    UNION ALL

    -- 2) 类型为 2 (散货/普通货物) 的出库数量 (_XORN = 'X')
    SELECT B.MA_KNQ, B.MA_KH, A.DINH_DANH_HANG_HOA, 
           CASE WHEN B.DHOPDONGID IS NULL THEN (SELECT TOP 1 DHOPDONGID FROM DPHIEU P WHERE MA_KNQ = '你的保税仓代码' AND _XORN = 'N' AND TYPE = '2' AND SO_PHIEU = (A.SO_PHIEU_N)) ELSE B.DHOPDONGID END, 
           NULL, NULL, NULL, B.SO_PHIEU, B.NGAY_PHIEU, (A.SO_LUONG)
    FROM DPHIEU_HANG A 
    INNER JOIN DPHIEU B ON A.DPHIEUID = B.DPHIEUID
    WHERE B.MA_KNQ = '你的保税仓代码' AND B._XORN = 'X' AND B.TRANG_THAI = 'T' AND ISNULL(A.IS_HUY, 0) = 0 AND B.TYPE = 2 
      AND EXISTS (SELECT 1 FROM DPHIEU_HANG C INNER JOIN DPHIEU X ON C.DPHIEUID=X.DPHIEUID WHERE X.MA_KNQ = '你的保税仓代码' AND A.DINH_DANH_HANG_HOA = C.DINH_DANH_HANG_HOA AND A.SO_PHIEU_N=X.SO_PHIEU AND X._XORN = 'N' AND X.TRANG_THAI = 'T' AND X.TYPE = '2' AND X.DHOPDONGID IN(SELECT DHOPDONGID FROM #DHOPDONG) AND ISNULL(C.IS_HUY, 0) = 0)

    UNION ALL 

    -- 3) 类型为 1 (集装箱货物) 的入库数量 (_XORN = 'N') 且未拆箱 (IS_RUTHANG = 0)
    SELECT B.MA_KNQ, C.MA_KH, A.DINH_DANH_HANG_HOA, B.DHOPDONGID, B.SO_PHIEU, B.NGAY_PHIEU, 
           (A.SO_LUONG) AS SO_LUONG, CAST(NULL AS VARCHAR) AS SO_PHIEU_XUAT, CAST(NULL AS DATETIME) AS NGAY_PHIEU_XUAT, CAST(NULL AS FLOAT) AS SO_LUONG_GETOUT 
    FROM DPHIEU_HANG A 
    INNER JOIN DPHIEU B ON A.DPHIEUID = B.DPHIEUID 
    INNER JOIN DHOPDONG C ON B.DHOPDONGID = C.DHOPDONGID 
    INNER JOIN DCONTAINER D ON B.DPHIEUID = D.DPHIEUID AND A.SO_CONT = D.SO_CONT
    WHERE B.MA_KNQ = '你的保税仓代码' AND B._XORN = 'N' AND B.TRANG_THAI = 'T' 
      AND ISNULL(A.IS_HUY, 0) = 0 AND B.TYPE = 1 AND D.IS_RUTHANG = 0 
      AND B.DHOPDONGID IN (SELECT DHOPDONGID FROM #DHOPDONG)

    UNION ALL 

    -- 4) 类型为 1 (集装箱货物) 的出库数量 (_XORN = 'X')
    SELECT B.MA_KNQ, B.MA_KH, A.DINH_DANH_HANG_HOA, 
           CASE WHEN B.DHOPDONGID IS NULL THEN (SELECT TOP 1 DHOPDONGID FROM DPHIEU P WHERE MA_KNQ = '你的保税仓代码' AND _XORN = 'N' AND TYPE = '1' AND SO_PHIEU = (A.SO_PHIEU_N)) ELSE B.DHOPDONGID END, 
           NULL, NULL, NULL, B.SO_PHIEU, B.NGAY_PHIEU, (A.SO_LUONG) 
    FROM DPHIEU_HANG A 
    INNER JOIN DPHIEU B ON A.DPHIEUID = B.DPHIEUID  
    INNER JOIN DCONTAINER D ON B.DPHIEUID = D.DPHIEUID AND A.SO_CONT = D.SO_CONT
    WHERE B.MA_KNQ = '你的保税仓代码' AND B._XORN = 'X' AND B.TRANG_THAI = 'T' AND ISNULL(A.IS_HUY, 0) = 0 AND B.TYPE = 1 
      AND EXISTS (SELECT 1 FROM DCONTAINER E WHERE D.DPHIEU_NHAPID = E.DPHIEUID AND D.SO_CONT = E.SO_CONT AND E.IS_RUTHANG = 0)
      AND EXISTS (SELECT 1 FROM DPHIEU_HANG C INNER JOIN DPHIEU X ON C.DPHIEUID=X.DPHIEUID WHERE X.MA_KNQ = '你的保税仓代码' AND A.DINH_DANH_HANG_HOA = C.DINH_DANH_HANG_HOA AND A.SO_PHIEU_N=X.SO_PHIEU AND X._XORN = 'N' AND X.TRANG_THAI = 'T' AND X.TYPE = '1' AND X.DHOPDONGID IN(SELECT DHOPDONGID FROM #DHOPDONG) AND ISNULL(C.IS_HUY, 0) = 0)
) A 
LEFT JOIN DHOPDONG C ON A.DHOPDONGID = C.DHOPDONGID AND A.MA_KNQ = C.MA_KNQ 
WHERE A.MA_KNQ = '你的保税仓代码' AND A.DHOPDONGID IN (SELECT DHOPDONGID FROM #DHOPDONG)
GROUP BY A.MA_KNQ, A.DHOPDONGID, SO_HD;

-- STEP 3: 回填入库和出库数量，并计算库存余额（TON）
UPDATE #DHOPDONG 
SET SO_LUONG_GETIN = ISNULL(B.SO_LUONG, 0), 
    SO_LUONG_GETOUT = ISNULL(B.SO_LUONG_GETOUT, 0) 
FROM #DHOPDONG A, #DPHIEU B 
WHERE A.MA_KNQ = B.MA_KNQ AND A.DHOPDONGID = B.DHOPDONGID;

-- 核心公式：库存 = 进库数量 - 出库数量
UPDATE #DHOPDONG SET SO_LUONG_TON = SO_LUONG_GETIN - SO_LUONG_GETOUT;

-- STEP 4: 终极过滤（重点！！）
DELETE #DHOPDONG WHERE SO_LUONG_GETIN = 0;                        -- 删掉没有入库记录的合同
DELETE #DHOPDONG WHERE CAST(SO_LUONG_TON AS NUMERIC(20,4)) <> 0;   -- 【关键】删掉库存不等于0的合同！！

-- STEP 5: 输出最终结果并销毁临时表
SELECT * FROM #DHOPDONG A ORDER BY A.MA_KNQ, A.DHOPDONGID, SO_HD, A.MA_KH;

DROP TABLE #DPHIEU, #DHOPDONG;