-- ====================================================================
-- 【终极完整纯查询版】ECUS5 保税仓 FIFO 实时结存与库龄总账 (OnHand)
-- （无权限门槛，列名与系统原生字段 100% 一致，附带详尽中文业务注释）
-- ====================================================================
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

-- ========================================
-- 🔻 请在这里修改你的查询参数 🔻
-- ========================================
DECLARE @MaKNQ NVARCHAR(50) = 'VNNSL';          -- ★ 必须修改：例如 'VNNSL'
DECLARE @TargetDate DATETIME = GETDATE();       -- 默认盘点截止到今天此刻，也可改为特定日期如 '2026-05-17'

-- --------------------------------------------------------------------
-- STEP 1: 提取所有【集装箱重箱（Type = 1）】的原始入库基础账
-- --------------------------------------------------------------------
IF OBJECT_ID('tempdb..#NHAP') IS NOT NULL DROP TABLE #NHAP;

SELECT 
    CAST(CAST(A.DHOPDONGID AS VARCHAR) + ';' + CAST(A.TYPE AS VARCHAR) + ';' + CAST(B.DINH_DANH_HANG_HOA AS VARCHAR) + ';' AS NVARCHAR(100)) AS CKEYS, 
    A.DHOPDONGID, A.TYPE, A.SO_PHIEU, A.NGAY_PHIEU, A.DPHIEUID, A.SO_HD, A.NGAY_HD, A.MA_NGUON, A.MA_NT, A.TY_GIA_VND,
    B.DPHIEU_HANGID, B.SO_TK, CAST(B.NGAY_DK AS DATE) AS NGAY_DK, F.NGAY_NHAP, B.NGAY_VAO_RA, B.DINH_DANH_HANG_HOA, 
    B.MA_SP, B.TEN_SP, B.STTHANG, B.MA_NUOC, B.SO_LUONG, B.MA_DVT, B.TRONG_LUONG_GW, B.TRONG_LUONG_NW, 
    B.DON_GIA AS GIA_NHAP, B.TRI_GIA, B.MA_HS, B.VI_TRI_HANG, B.SO_CONT, 
    D.SO_SEAL, S.TEN_NGUON, T.TEN_DVT, G.TEN_KH, CAST('' AS NVARCHAR(100)) AS GHI_CHU
INTO #NHAP 
FROM DPHIEU A WITH (NOLOCK)
INNER JOIN DPHIEU_HANG B WITH (NOLOCK) ON A.DPHIEUID = B.DPHIEUID AND ISNULL(B.IS_HUY, 0) = 0
INNER JOIN DCONTAINER D WITH (NOLOCK) ON D.DPHIEUID = A.DPHIEUID AND D.SO_CONT = B.SO_CONT AND ISNULL(D.IS_HUY, 0) = 0 AND D.IS_RUTHANG = 0 
LEFT JOIN DHOPDONG F WITH (NOLOCK) ON A.DHOPDONGID = F.DHOPDONGID 
LEFT JOIN SKHACHHANG G WITH (NOLOCK) ON G.MA_KH = F.MA_KH AND F.MA_KNQ = G.MA_KNQ
LEFT JOIN SNGUONHANG S WITH (NOLOCK) ON S.MA_NGUON = A.MA_NGUON 
LEFT JOIN SDVT T WITH (NOLOCK) ON B.MA_DVT = T.MA_DVT
WHERE A.MA_KNQ = @MaKNQ AND A.TYPE = 1 AND A._XORN = 'N' AND A.TRANG_THAI = 'T' 
  AND ((A.PB_PHIEU = 'CT' AND A.DPHIEUID_NEXT IS NULL) OR (A.PB_PHIEU = 'SU' AND A.DPHIEUID_PREV IS NOT NULL))
  AND A.NGAY_PHIEU <= @TargetDate;

-- --------------------------------------------------------------------
-- STEP 2: 洗涤账目：扣减掉已经在库内卸货拆箱（Rút hàng）的空箱行
-- --------------------------------------------------------------------
IF OBJECT_ID('tempdb..#DRUTHANG') IS NOT NULL DROP TABLE #DRUTHANG;

SELECT A.DPHIEUID, A.SO_CONT, B.SO_DINH_DANH AS DINH_DANH_HANG_HOA 
INTO #DRUTHANG FROM DRUTHANG A WITH (NOLOCK)
INNER JOIN DRUTHANG_CT B WITH (NOLOCK) ON A.DRUTHANGID = B.DRUTHANGID
WHERE A.MA_KNQ = @MaKNQ AND A.TRANG_THAI = 2 
GROUP BY A.DPHIEUID, A.SO_CONT, B.SO_DINH_DANH;

DELETE #NHAP FROM #NHAP A, #DRUTHANG B WHERE A.DPHIEUID = B.DPHIEUID AND A.SO_CONT = B.SO_CONT;
DROP TABLE #DRUTHANG;

-- --------------------------------------------------------------------
-- STEP 3: 追加写入所有【普通散货 / 件货（Type = 2）】的原始入库明细
-- --------------------------------------------------------------------
INSERT INTO #NHAP 
SELECT 
    CAST(CAST(A.DHOPDONGID AS VARCHAR) + ';' + CAST(A.TYPE AS VARCHAR) + ';' + CAST(B.DINH_DANH_HANG_HOA AS VARCHAR) + ';' AS NVARCHAR(100)) AS CKEYS, 
    A.DHOPDONGID, A.TYPE, A.SO_PHIEU, A.NGAY_PHIEU, A.DPHIEUID, A.SO_HD, A.NGAY_HD, A.MA_NGUON, A.MA_NT, A.TY_GIA_VND,
    B.DPHIEU_HANGID, B.SO_TK, CAST(B.NGAY_DK AS DATE) AS NGAY_DK, F.NGAY_NHAP, B.NGAY_VAO_RA, B.DINH_DANH_HANG_HOA, 
    B.MA_SP, B.TEN_SP, B.STTHANG, B.MA_NUOC, B.SO_LUONG, B.MA_DVT, B.TRONG_LUONG_GW, B.TRONG_LUONG_NW, 
    B.DON_GIA AS GIA_NHAP, B.TRI_GIA, B.MA_HS, B.VI_TRI_HANG, B.SO_CONT, 
    '' AS SO_SEAL, S.TEN_NGUON, T.TEN_DVT, G.TEN_KH, CAST('' AS NVARCHAR(100)) AS GHI_CHU
FROM DPHIEU A WITH (NOLOCK)
INNER JOIN DPHIEU_HANG B WITH (NOLOCK) ON A.DPHIEUID = B.DPHIEUID AND ISNULL(B.IS_HUY, 0) = 0
LEFT JOIN DHOPDONG F WITH (NOLOCK) ON A.DHOPDONGID = F.DHOPDONGID 
LEFT JOIN SKHACHHANG G WITH (NOLOCK) ON G.MA_KH = F.MA_KH AND F.MA_KNQ = G.MA_KNQ
LEFT JOIN SNGUONHANG S WITH (NOLOCK) ON S.MA_NGUON = A.MA_NGUON 
LEFT JOIN SDVT T WITH (NOLOCK) ON B.MA_DVT = T.MA_DVT
WHERE A.MA_KNQ = @MaKNQ AND A.TYPE = 2 AND A._XORN = 'N' AND A.TRANG_THAI = 'T' 
  AND ((A.PB_PHIEU = 'CT' AND A.DPHIEUID_NEXT IS NULL) OR (A.PB_PHIEU = 'SU' AND A.DPHIEUID_PREV IS NOT NULL))
  AND A.NGAY_PHIEU <= @TargetDate;

-- --------------------------------------------------------------------
-- STEP 4: 汇集全量截止日前的【分批正常出库及海关监督销毁出库流水】
-- --------------------------------------------------------------------
IF OBJECT_ID('tempdb..#XUAT') IS NOT NULL DROP TABLE #XUAT;

SELECT CAST('' AS NVARCHAR(100)) AS CKEYS, A.TYPE, A.DHOPDONGID, A.SO_HD, MAX(A.NGAY_PHIEU) AS NGAY_XUAT, B.SO_PHIEU_N, B.MA_SP, B.DINH_DANH_HANG_HOA, ROUND(SUM(B.SO_LUONG), 4) AS SO_LUONG, MAX(B.NGAY_VAO_RA) AS NGAY_GETOUT, 0 AS IS_TIEU_HUY
INTO #XUAT FROM DPHIEU A WITH (NOLOCK)
INNER JOIN DPHIEU_HANG B WITH (NOLOCK) ON (A.DPHIEUID = B.DPHIEUID AND ISNULL(B.IS_HUY, 0) = 0) 
INNER JOIN DCONTAINER DF WITH (NOLOCK) ON DF.DPHIEUID = A.DPHIEUID AND DF.IS_RUTHANG = 0 AND DF.TINH_TRANG = 1 AND A.DRUTHANGID IS NULL 
WHERE A.MA_KNQ = @MaKNQ AND A.TYPE = 1 AND A._XORN = 'X' AND A.MA_NGUON <> 'X4' AND A.TRANG_THAI = 'T'
  AND ((A.PB_PHIEU = 'CT' AND A.DPHIEUID_NEXT IS NULL) OR (A.PB_PHIEU = 'SU' AND A.DPHIEUID_PREV IS NOT NULL)) AND A.NGAY_PHIEU <= @TargetDate
GROUP BY A.TYPE, A.DHOPDONGID, A.SO_HD, B.SO_PHIEU_N, B.MA_SP, B.DINH_DANH_HANG_HOA;

INSERT INTO #XUAT 
SELECT CAST('' AS NVARCHAR(100)) AS CKEYS, A.TYPE, A.DHOPDONGID, A.SO_HD, MAX(A.NGAY_PHIEU) AS NGAY_XUAT, B.SO_PHIEU_N, B.MA_SP, B.DINH_DANH_HANG_HOA, ROUND(SUM(B.SO_LUONG), 4) AS SO_LUONG, MAX(B.NGAY_VAO_RA) AS NGAY_GETOUT, 0 AS IS_TIEU_HUY
FROM DPHIEU A WITH (NOLOCK)
INNER JOIN DPHIEU_HANG B WITH (NOLOCK) ON (A.DPHIEUID = B.DPHIEUID AND ISNULL(B.IS_HUY, 0) = 0) 
WHERE A.MA_KNQ = @MaKNQ AND A.TYPE = 2 AND A._XORN = 'X' AND A.MA_NGUON <> 'X4' AND A.TRANG_THAI = 'T'
  AND ((A.PB_PHIEU = 'CT' AND A.DPHIEUID_NEXT IS NULL) OR (A.PB_PHIEU = 'SU' AND A.DPHIEUID_PREV IS NOT NULL)) AND A.NGAY_PHIEU <= @TargetDate
GROUP BY A.TYPE, A.DHOPDONGID, A.SO_HD, B.SO_PHIEU_N, B.MA_SP, B.DINH_DANH_HANG_HOA;

INSERT INTO #XUAT 
SELECT CAST('' AS NVARCHAR(100)) AS CKEYS, 2 AS TYPE, A.DHOPDONGID, A.SO_HD, B.NGAY_PHIEU AS NGAY_XUAT, A.SO_PHIEU_N, A.MA_SP, A.DINH_DANH_HANG_HOA, ROUND(A.SO_LUONG, 4) AS SO_LUONG, NULL AS NGAY_GETOUT, 1 AS IS_TIEU_HUY
FROM DTIEUHUY_CT A WITH (NOLOCK) INNER JOIN DTIEUHUY B WITH (NOLOCK) ON A.DTIEUHUYID = B.DTIEUHUYID
WHERE B.MA_KNQ = @MaKNQ AND B.TRANG_THAI = 1 AND B.NGAY_PHIEU <= @TargetDate;

-- --------------------------------------------------------------------
-- STEP 5: 提取所有权虚转网（#DVANBAN），连环穿透校正实物原始日期
-- --------------------------------------------------------------------
IF OBJECT_ID('tempdb..#DVANBAN') IS NOT NULL DROP TABLE #DVANBAN;
IF OBJECT_ID('tempdb..#NHAP_X') IS NOT NULL DROP TABLE #NHAP_X;

SELECT CAST(CAST(DHOPDONGID_GUI AS VARCHAR) + ';' + CAST(TYPE AS VARCHAR) + ';' + CAST(DINH_DANH_HANG_HOA AS VARCHAR) + ';' AS NVARCHAR(100)) AS CKEYS, B.DVANBANID, B.DHOPDONGID_GUI, F.SO_HD AS SO_HD_GUI, B.DHOPDONGID_NHAN, G.SO_HD AS SO_HD_NHAN, B.SOTK, A.TYPE, A.SO_PHIEU_N, A.STTHANG_N, A.MA_SP, A.DINH_DANH_HANG_HOA, A.SO_LUONG, A.TRI_GIA, F.NGAY_NHAP, CAST(NULL AS DATETIME) AS NGAY_VAO_RA
INTO #DVANBAN FROM DVANBAN_HANG A, DVANBAN B, DHOPDONG F, DHOPDONG G
WHERE B.MA_KNQ = @MaKNQ AND B.TRANG_THAI = '2' AND A.DVANBANID = B.DVANBANID AND B.DHOPDONGID_GUI = F.DHOPDONGID AND B.DHOPDONGID_NHAN = G.DHOPDONGID AND B.NGAY_CHUYEN_QUYEN <= @TargetDate;

SELECT CAST('' AS NVARCHAR(100)) AS CKEYS, A.TYPE, A.SO_PHIEU, A.MA_NGUON, A.DHOPDONGID, A.SO_HD, A.NGAY_HD, A.NGAY_HHHD, B.SO_TK, B.NGAY_DK, B.DINH_DANH_HANG_HOA, F.NGAY_NHAP, B.NGAY_VAO_RA
INTO #NHAP_X FROM DPHIEU A INNER JOIN DPHIEU_HANG B ON A.DPHIEUID = B.DPHIEUID LEFT JOIN DHOPDONG F ON A.DHOPDONGID = F.DHOPDONGID 
WHERE A.MA_KNQ = @MaKNQ AND A._XORN = 'N' AND A.TRANG_THAI = 'T' AND A.NGAY_PHIEU <= @TargetDate
GROUP BY A.TYPE, A.SO_PHIEU, A.MA_NGUON, A.DHOPDONGID, A.SO_HD, A.NGAY_HD, A.NGAY_HHHD, B.SO_TK, B.NGAY_DK, B.DINH_DANH_HANG_HOA, F.NGAY_NHAP, B.NGAY_VAO_RA;

-- 执行 5 代所有权追随回归
DECLARE @c INT = 1, @d INT = 0;
WHILE ((@c <= 5) AND @d = 0) 
BEGIN 
    UPDATE #DVANBAN SET NGAY_VAO_RA = B.NGAY_VAO_RA FROM #DVANBAN A, #NHAP_X B WHERE A.TYPE = B.TYPE AND A.DHOPDONGID_GUI = B.DHOPDONGID AND A.SO_PHIEU_N = B.SO_PHIEU AND A.DINH_DANH_HANG_HOA = B.DINH_DANH_HANG_HOA AND B.NGAY_VAO_RA IS NOT NULL; 
    UPDATE #NHAP SET NGAY_NHAP = B.NGAY_NHAP, NGAY_VAO_RA = B.NGAY_VAO_RA FROM #NHAP A, #DVANBAN B WHERE A.TYPE = B.TYPE AND A.MA_NGUON = 'N4' AND A.DHOPDONGID = B.DHOPDONGID_NHAN AND A.DINH_DANH_HANG_HOA = B.DINH_DANH_HANG_HOA AND B.NGAY_VAO_RA IS NOT NULL; 
    UPDATE #NHAP_X SET NGAY_NHAP = B.NGAY_NHAP, NGAY_VAO_RA = B.NGAY_VAO_RA FROM #NHAP_X A, #DVANBAN B WHERE A.TYPE = B.TYPE AND A.MA_NGUON = 'N4' AND A.DHOPDONGID = B.DHOPDONGID_NHAN AND A.DINH_DANH_HANG_HOA = B.DINH_DANH_HANG_HOA AND B.NGAY_VAO_RA IS NOT NULL; 
    IF NOT EXISTS(SELECT 1 FROM #DVANBAN WHERE NGAY_VAO_RA IS NULL) AND NOT EXISTS(SELECT 1 FROM #NHAP_X WHERE NGAY_VAO_RA IS NULL) AND NOT EXISTS(SELECT 1 FROM #NHAP WHERE NGAY_VAO_RA IS NULL) SELECT @d = 1; 
    SET @c += 1;
END;

-- --------------------------------------------------------------------
-- STEP 6: 对冲剥离纸面虚拟合同转让 (内部过户对冲)
-- --------------------------------------------------------------------
IF OBJECT_ID('tempdb..#NHAP2') IS NOT NULL DROP TABLE #NHAP2;
IF OBJECT_ID('tempdb..#DVANBAN2') IS NOT NULL DROP TABLE #DVANBAN2;

SELECT ROW_NUMBER() OVER(PARTITION BY CKEYS ORDER BY NGAY_PHIEU, DPHIEUID, DPHIEU_HANGID) AS STT, *, SO_LUONG AS SO_LUONG2, TRI_GIA AS TRI_GIA2, 0*SO_LUONG AS SO_LUONG_SD, TRI_GIA AS TRI_GIA_SD, 0*TRI_GIA AS TRI_GIA_TON, 0*SO_LUONG AS LUONG_XUAT, 0*SO_LUONG AS LUONG_TON, CAST (NULL AS DATE) AS NGAY_XUAT, CAST (NULL AS INT) AS SO_NGAY_TON 
INTO #NHAP2 FROM #NHAP;

SELECT CKEYS, SUM(SO_LUONG) AS SO_LUONG, 0*SUM(SO_LUONG) AS SO_LUONG_SD, SUM(SO_LUONG) AS SO_LUONG_TON, SUM(TRI_GIA) AS TRI_GIA, 0*SUM(TRI_GIA) AS TRI_GIA_SD, SUM(TRI_GIA) AS TRI_GIA_TON 
INTO #DVANBAN2 FROM #DVANBAN A GROUP BY CKEYS;

DECLARE @x INT = 1, @y INT = ISNULL((SELECT MAX(STT) FROM #NHAP2), 1);
WHILE (@x <= @y)
BEGIN
    UPDATE #NHAP2 SET SO_LUONG_SD = CASE WHEN B.SO_LUONG_TON > A.SO_LUONG THEN A.SO_LUONG ELSE B.SO_LUONG_TON END, TRI_GIA_SD = CASE WHEN B.TRI_GIA_TON > A.TRI_GIA THEN A.TRI_GIA ELSE B.TRI_GIA_TON END FROM #NHAP2 A, #DVANBAN2 B WHERE A.CKEYS = B.CKEYS AND B.SO_LUONG_TON > 0 AND STT = @x;
    UPDATE #DVANBAN2 SET SO_LUONG_SD = B.SO_LUONG_SD, TRI_GIA_SD = B.TRI_GIA_SD FROM #DVANBAN2 A, (SELECT CKEYS, SUM(SO_LUONG_SD) SO_LUONG_SD, SUM(TRI_GIA_SD) TRI_GIA_SD FROM #NHAP2 WHERE SO_LUONG_SD > 0 GROUP BY CKEYS) B WHERE A.CKEYS = B.CKEYS;
    UPDATE #DVANBAN2 SET SO_LUONG_TON = SO_LUONG - SO_LUONG_SD, TRI_GIA_TON = TRI_GIA - TRI_GIA_SD;
    SET @x += 1;
END;

UPDATE #NHAP2 SET SO_LUONG = SO_LUONG2 - SO_LUONG_SD, TRI_GIA = TRI_GIA2 - TRI_GIA_SD;
DELETE #NHAP2 WHERE SO_LUONG = 0;

UPDATE #NHAP_X SET CKEYS = CAST(TYPE AS VARCHAR) + ';' + CAST(SO_PHIEU AS VARCHAR) + ';' + CAST(DINH_DANH_HANG_HOA AS VARCHAR) + ';';
UPDATE #XUAT SET CKEYS = CAST(TYPE AS VARCHAR) + ';' + CAST(SO_PHIEU_N AS VARCHAR) + ';' + CAST(DINH_DANH_HANG_HOA AS VARCHAR) + ';';
UPDATE #XUAT SET DHOPDONGID = B.DHOPDONGID, SO_HD = B.SO_HD FROM #XUAT A, #NHAP_X B WHERE A.CKEYS = B.CKEYS;

IF OBJECT_ID('tempdb..#XUAT2') IS NOT NULL DROP TABLE #XUAT2;
SELECT ROW_NUMBER() OVER(PARTITION BY DHOPDONGID, TYPE, DINH_DANH_HANG_HOA ORDER BY DHOPDONGID, TYPE, DINH_DANH_HANG_HOA, NGAY_XUAT) AS STT, CAST(CAST(DHOPDONGID AS VARCHAR) + ';' + CAST(TYPE AS VARCHAR) + ';' + CAST(DINH_DANH_HANG_HOA AS VARCHAR) + ';' AS NVARCHAR(100)) AS CKEYS, DHOPDONGID, TYPE, DINH_DANH_HANG_HOA, NGAY_XUAT, SUM(SO_LUONG) AS SO_LUONG, 0*SUM(SO_LUONG) AS LUONG_XUAT, SUM(SO_LUONG) AS LUONG_TON, 0*SUM(SO_LUONG) AS TONG_NHAP, 0*SUM(SO_LUONG) AS TONG_XUAT, SUM(SO_LUONG) AS TONG_TON, 0 AS IS_TIEU_HUY
INTO #XUAT2 FROM #XUAT GROUP BY DHOPDONGID, TYPE, DINH_DANH_HANG_HOA, NGAY_XUAT;

UPDATE #XUAT2 SET TONG_NHAP = B.SO_LUONG, TONG_TON = B.SO_LUONG FROM #XUAT2 A, (SELECT CKEYS, SUM(SO_LUONG) AS SO_LUONG FROM #XUAT2 GROUP BY CKEYS) B WHERE A.CKEYS = B.CKEYS;
UPDATE #XUAT2 SET IS_TIEU_HUY = 1 FROM #XUAT2 A, #XUAT B WHERE A.TYPE = B.TYPE AND A.DHOPDONGID = B.DHOPDONGID AND A.DINH_DANH_HANG_HOA = B.DINH_DANH_HANG_HOA AND B.IS_TIEU_HUY = 1;

DROP TABLE #NHAP, #XUAT, #NHAP_X, #DVANBAN, #DVANBAN2;

-- --------------------------------------------------------------------
-- STEP 7: 【终极 FIFO 核心核销引擎】双层 WHILE 冲抵分摊计算
-- --------------------------------------------------------------------
UPDATE #NHAP2 SET LUONG_TON = SO_LUONG - LUONG_XUAT, SO_LUONG_SD = 0;

DECLARE @stop INT = 0;
WHILE (@stop = 0)
BEGIN
    IF OBJECT_ID('tempdb..#XUAT3') IS NOT NULL DROP TABLE #XUAT3;
    SELECT A.* INTO #XUAT3 FROM #XUAT2 A, (SELECT CKEYS, MIN(STT) AS STT FROM #XUAT2 WHERE LUONG_TON > 0 GROUP BY CKEYS) B WHERE A.CKEYS = B.CKEYS AND A.STT = B.STT;
    
    DECLARE @stop2 INT = 0;
    WHILE (@stop2 = 0)
    BEGIN
        IF OBJECT_ID('tempdb..#NHAP3') IS NOT NULL DROP TABLE #NHAP3;
        SELECT A.* INTO #NHAP3 FROM #NHAP2 A, (SELECT CKEYS, MIN(STT) AS STT FROM #NHAP2 WHERE LUONG_TON > 0 GROUP BY CKEYS) B WHERE A.CKEYS = B.CKEYS AND A.STT = B.STT;
        
        IF NOT EXISTS(SELECT 1 FROM #XUAT3 A, #NHAP3 B WHERE A.CKEYS = B.CKEYS AND A.LUONG_TON > 0 AND B.LUONG_TON > 0) SET @stop2 = 1;
        
        UPDATE #NHAP3 SET NGAY_XUAT = B.NGAY_XUAT, SO_LUONG_SD = CASE WHEN B.LUONG_TON > A.LUONG_TON THEN A.LUONG_TON ELSE B.LUONG_TON END FROM #NHAP3 A, #XUAT3 B WHERE A.CKEYS = B.CKEYS AND B.LUONG_TON > 0 AND A.LUONG_TON > 0;
        UPDATE #NHAP3 SET LUONG_XUAT += SO_LUONG_SD;
        UPDATE #XUAT3 SET LUONG_XUAT += B.SO_LUONG_SD FROM #XUAT3 A, #NHAP3 B WHERE A.CKEYS = B.CKEYS;
        UPDATE #XUAT3 SET LUONG_TON = SO_LUONG - LUONG_XUAT;
        UPDATE #NHAP3 SET LUONG_TON = SO_LUONG - LUONG_XUAT;
        UPDATE #NHAP2 SET LUONG_XUAT = B.LUONG_XUAT, LUONG_TON = B.LUONG_TON, NGAY_XUAT = B.NGAY_XUAT FROM #NHAP2 A, #NHAP3 B WHERE A.CKEYS = B.CKEYS AND A.STT = B.STT;
        DROP TABLE #NHAP3;
    END;
    UPDATE #XUAT2 SET LUONG_XUAT = B.LUONG_XUAT, LUONG_TON = B.LUONG_TON FROM #XUAT2 A, #XUAT3 B WHERE A.CKEYS = B.CKEYS AND A.STT = B.STT;
    IF NOT EXISTS(SELECT 1 FROM #XUAT2 A, #NHAP2 B WHERE A.CKEYS = B.CKEYS AND A.LUONG_TON > 0 AND B.LUONG_TON > 0) SET @stop = 1;
    DROP TABLE #XUAT3;
END;

-- --------------------------------------------------------------------
-- STEP 8: 【斩杀与最终输出】对齐系统原始英文字段与 Excel 排序
-- --------------------------------------------------------------------
UPDATE #NHAP2 SET TRI_GIA_TON = ISNULL(LUONG_TON * GIA_NHAP * TY_GIA_VND, 0);
UPDATE #NHAP2 SET GHI_CHU = CASE WHEN A.GHI_CHU = '' THEN '' ELSE A.GHI_CHU + ', ' END + N'Có hàng tiêu hủy' FROM #NHAP2 A, #XUAT2 B WHERE A.CKEYS = B.CKEYS AND B.IS_TIEU_HUY = 1;

-- 【绝杀清零】：扣减完没余额的货，直接物理删除！只留纯正的 OnHand 实存！
DELETE #NHAP2 WHERE ROUND(LUONG_TON, 4) <= 0;

-- 动态计算精准库龄
UPDATE #NHAP2 SET SO_NGAY_TON = DATEDIFF(dd, NGAY_NHAP, @TargetDate) + 1;

-- ====================================================================
-- 终极输出：抛弃中文别名，完美对齐 ECUS5 数据库原生列名，并附加详尽业务注释
-- ====================================================================
SELECT 
    SO_PHIEU,             -- [入库单] 初始入库单号 (Số phiếu)
    NGAY_PHIEU,           -- [入库单] 初始入仓日期 (Ngày phiếu)
    SO_HD,                -- [合规] 保税合同号 (Số hợp đồng)
    NGAY_HD,              -- [合规] 保税合同录入日期 (Ngày hợp đồng)
    MA_NGUON,             -- [来源] 货物来源属性代码 (Mã nguồn)
    SO_TK,                -- [报关] 海关进口报关单号 (Số tờ khai)
    NGAY_DK,              -- [报关] 报关单申报注册日期 (Ngày đăng ký)
    NGAY_NHAP,            -- [溯源] 原始真实入库日期 (Ngày nhập)
    DINH_DANH_HANG_HOA,   -- [溯源] 货物海关唯一定标码 (Định danh hàng hóa)
    MA_SP,                -- [商品] 内部商品编码 (Mã sản phẩm)
    TEN_SP,               -- [商品] 商品综合品名 (Tên sản phẩm)
    MA_NUOC,              -- [商品] 原产国代码 (Mã nước)
    MA_HS,                -- [报关] 海关HS税号 (Mã HS)
    SO_LUONG AS LUONG_NHAP, -- [物控] 原始到货总量 (Lượng nhập)
    LUONG_XUAT,           -- [物控] 已被领走/出库数量 (Lượng xuất)
    LUONG_TON,            -- [物控] ★ 当前在库实物结存数量 (Lượng tồn)
    MA_DVT,               -- [物控] 计量单位编码 (Mã ĐVT)
    TRONG_LUONG_GW,       -- [物控] 毛重-Gross Weight (Trọng lượng GW)
    TRONG_LUONG_NW,       -- [物控] 净重-Net Weight (Trọng lượng NW)
    GIA_NHAP,             -- [财务] 原始进口单价 (Đơn giá nhập)
    TRI_GIA_TON,          -- [财务] ★ 当前结存总资产价值 (Trị giá tồn)
    VI_TRI_HANG,          -- [仓配] 仓库物理货位格 (Vị trí hàng)
    SO_CONT,              -- [仓配] 集装箱柜号 (Số Container)
    SO_SEAL,              -- [仓配] 海关铅封号 (Số Seal)
    TEN_NGUON,            -- [字典] 货物来源类型说明 (Tên nguồn)
    TEN_DVT,              -- [字典] 计量单位名称说明 (Tên ĐVT)
    TEN_KH,               -- [客户] 货主客户名称 (Tên khách hàng)
    SO_NGAY_TON,          -- [库龄] ★ 该批货物实际滞库天数 (Số ngày tồn)
    GHI_CHU               -- [其他] 系统级动作备注 (Ghi chú)
FROM #NHAP2 
ORDER BY NGAY_PHIEU ASC, SO_PHIEU ASC, STTHANG ASC;

-- 清理现场
DROP TABLE #NHAP2, #XUAT2;