/*  

深度业务逻辑解密（为什么这段代码对你极有价值？）
库龄计算公式揭秘 (DATEDIFF)：
代码里的 NGAY_LUU_KHO = DATEDIFF(D, NGAY_NHAP, GETDATE()) 表明，海关系统计算货物在保税仓里呆了多少天，是用今天的系统时间减去合同的入库日期（NGAY_NHAP）。

精确到 4 位小数的库存控制：
在做库存清零判断时，系统使用了 CAST(SO_LUONG_TON AS NUMERIC(20,4)) = 0。这意味着如果由于系统浮点数运算导致出现 0.00001 这样的微小残余，只要在 4 位小数内为 0，就会被直接视为无库存，从而在报表中被 DELETE 剔除。

类型隔离 (TYPE = 2)：
请注意，这段代码只过滤了 B.TYPE = 2。结合我们之前的分析，说明这个特定的查询菜单是专门针对“散货/件货”进行库存盘点的，它并没有包含 Container（集装箱，即 TYPE = 1）的库存。如果你们仓库既有集装箱又有散货，在对账时要尤其注意这一点。

有了这段 SQL 逻辑，你可以直接写个自动化脚本，天天在后台帮你跑每个保税合同的在库天数和准确余量，再也不用去系统界面上点点点导出了！

*/

-- STEP 1: 创建合同临时表，并初始化基础字段（包含库龄 NGAY_LUU_KHO 和项数 DONG_HANG）
SELECT A.MA_KNQ, A.DHOPDONGID, A.SO_HD, A.NGAY_NHAP, A.MA_KH, B.TEN_KH, 
       CAST(0 AS FLOAT) AS SO_LUONG_GETIN, 
       CAST(0 AS FLOAT) AS SO_LUONG_GETOUT, 
       CAST(0 AS FLOAT) AS SO_LUONG_TON, 
       CAST(0 AS FLOAT) AS NGAY_LUU_KHO, 
       CAST(0 AS FLOAT) AS DONG_HANG 
INTO #DHOPDONG 
FROM DHOPDONG A 
LEFT JOIN SKHACHHANG B ON A.MA_KNQ = B.MA_KNQ AND A.MA_KH = B.MA_KH 
WHERE A.MA_KNQ = '你的保税仓代码' --【变量：例如 'VNNSL'】

  --【动态过滤器 1：如果界面选了“开始日期” (flag)】
  -- AND A.NGAY_NHAP > '2026-01-01 23:59:59' 

  --【动态过滤器 2：如果界面选了“结束日期” (flag2)】
  -- AND A.NGAY_NHAP < '2026-05-17'

  --【动态过滤器 3：如果界面选了“客户代码” (flag3)】
  -- AND A.MA_KH = N'某个客户代码'

  --【动态过滤器 4：如果界面输入了“合同号” (flag4)】
  -- AND A.SO_HD = N'某个合同号'
;

-- STEP 2: 从出入库明细（DPHIEU_HANG）中按“货物唯一编码”汇总数量
SELECT A.MA_KNQ, A.DHOPDONGID, 
       CAST(SUM(SO_LUONG) AS NUMERIC(20,4)) AS SO_LUONG, 
       CAST(SUM(SO_LUONG_GETOUT) AS NUMERIC(20,4)) AS SO_LUONG_GETOUT, 
       SO_HD, 
       SUM(DONG_HANG) AS DONG_HANG, 
       SUM(DONG_HANG_X) AS DONG_HANG_X 
INTO #DPHIEU 
FROM ( 
    SELECT MA_KNQ, DHOPDONGID, DINH_DANH_HANG_HOA, 
           SUM(SO_LUONG) AS SO_LUONG, 
           SUM(SO_LUONG_GETOUT) AS SO_LUONG_GETOUT, 
           MAX(DONG_HANG) AS DONG_HANG, 
           MAX(DONG_HANG_X) AS DONG_HANG_X 
    FROM ( 
        -- 1) 类型为 2（散货）的正常入库单记录 (_XORN = 'N')
        SELECT B.MA_KNQ, C.MA_KH, A.DINH_DANH_HANG_HOA, B.DHOPDONGID, B.SO_PHIEU, B.NGAY_PHIEU, 
               (A.SO_LUONG) AS SO_LUONG, CAST(NULL AS VARCHAR) AS SO_PHIEU_XUAT, 
               CAST(NULL AS DATETIME) AS NGAY_PHIEU_XUAT, CAST(NULL AS FLOAT) AS SO_LUONG_GETOUT, 
               1 AS DONG_HANG, 0 AS DONG_HANG_X 
        FROM DPHIEU_HANG A 
        INNER JOIN DPHIEU B ON A.DPHIEUID = B.DPHIEUID 
        INNER JOIN DHOPDONG C ON B.DHOPDONGID = C.DHOPDONGID 
        WHERE B.MA_KNQ = '你的保税仓代码' AND B._XORN = 'N' AND B.TRANG_THAI = 'T' 
          AND ISNULL(A.IS_HUY, 0) = 0 AND B.TYPE = 2 
          AND B.DHOPDONGID IN (SELECT DHOPDONGID FROM #DHOPDONG)

        UNION ALL

        -- 2) 类型为 2（散货）的正常出库单记录 (_XORN = 'X')
        SELECT B.MA_KNQ, B.MA_KH, A.DINH_DANH_HANG_HOA, 
               CASE WHEN B.DHOPDONGID IS NULL THEN (SELECT TOP 1 DHOPDONGID FROM DPHIEU P INNER JOIN DPHIEU_HANG H ON P.DPHIEUID = H.DPHIEUID WHERE MA_KNQ = '你的保税仓代码' AND TYPE = 2 AND _XORN = 'N' AND H.DINH_DANH_HANG_HOA = A.DINH_DANH_HANG_HOA AND SO_PHIEU = (A.SO_PHIEU_N)) ELSE B.DHOPDONGID END AS DHOPDONGID, 
               NULL, NULL, NULL, B.SO_PHIEU, B.NGAY_PHIEU, (A.SO_LUONG), 
               0 AS DONG_HANG, 1 AS DONG_HANG_X 
        FROM DPHIEU_HANG A 
        INNER JOIN DPHIEU B ON A.DPHIEUID = B.DPHIEUID
        WHERE B.MA_KNQ = '你的保税仓代码' AND B._XORN = 'X' AND B.TRANG_THAI = 'T' AND ISNULL(A.IS_HUY, 0) = 0 AND B.TYPE = 2 
          AND EXISTS (SELECT 1 FROM DPHIEU_HANG C INNER JOIN DPHIEU X ON C.DPHIEUID=X.DPHIEUID WHERE X.MA_KNQ = '你的保税仓代码' AND A.DINH_DANH_HANG_HOA = C.DINH_DANH_HANG_HOA AND A.SO_PHIEU_N=X.SO_PHIEU AND X._XORN = 'N' AND X.TRANG_THAI = 'T' AND X.TYPE = '2' AND X.DHOPDONGID IN(SELECT DHOPDONGID FROM #DHOPDONG) AND ISNULL(C.IS_HUY, 0) = 0)
    ) T 
    GROUP BY MA_KNQ, DHOPDONGID, DINH_DANH_HANG_HOA 
) A 
LEFT JOIN DHOPDONG C ON A.DHOPDONGID = C.DHOPDONGID AND A.MA_KNQ = C.MA_KNQ 
WHERE A.MA_KNQ = '你的保税仓代码' AND A.DHOPDONGID IN (SELECT DHOPDONGID FROM #DHOPDONG)
GROUP BY A.MA_KNQ, A.DHOPDONGID, SO_HD;

-- STEP 3: 数据回填与核心业务计算
-- 1) 回填入库量、出库量和入库项数
UPDATE #DHOPDONG 
SET SO_LUONG_GETIN = ISNULL(B.SO_LUONG, 0), 
    SO_LUONG_GETOUT = ISNULL(B.SO_LUONG_GETOUT, 0), 
    DONG_HANG = B.DONG_HANG 
FROM #DHOPDONG A, #DPHIEU B 
WHERE A.MA_KNQ = B.MA_KNQ AND A.DHOPDONGID = B.DHOPDONGID;

-- 2) 如果入库项数为 0，则用出库项数补齐
UPDATE #DHOPDONG 
SET DONG_HANG = B.DONG_HANG_X 
FROM #DHOPDONG A, #DPHIEU B 
WHERE A.MA_KNQ = B.MA_KNQ AND A.DHOPDONGID = B.DHOPDONGID AND A.DONG_HANG = 0;

-- 3) 【核心计算】：库存余额 = 入库 - 出库； 库龄 = 当前时间 - 合同导入日期
UPDATE #DHOPDONG 
SET SO_LUONG_TON = SO_LUONG_GETIN - SO_LUONG_GETOUT, 
    NGAY_LUU_KHO = DATEDIFF(D, NGAY_NHAP, GETDATE());

-- STEP 4: 【关键过滤】
DELETE #DHOPDONG WHERE CAST(SO_LUONG_TON AS NUMERIC(20,4)) = 0; --【重点】斩断库存为0的合同！只留有货的！

--【动态过滤器 5 & 6：如果在界面上限制了“最少/最多在库天数” (flag5 / flag6)】
-- DELETE #DHOPDONG WHERE NGAY_LUU_KHO < 最小天数
-- DELETE #DHOPDONG WHERE NGAY_LUU_KHO > 最大天数

-- STEP 5: 最终输出报表结果
SELECT * FROM #DHOPDONG A ORDER BY A.MA_KNQ, A.DHOPDONGID, SO_HD, A.MA_KH;

-- 清理现场
DROP TABLE #DPHIEU, #DHOPDONG;