SELECT 
    wh_id,
    load_id,
    stage_loc,
    door_loc,
    carrier_id,
    trailer_type_id,
    status,
    work_type,
    trailer_number,
    bill_number,
    mode_id,
    shipment_status,
    earliest_ship_date,
    latest_ship_date,
    actual_ship_date,
    trigger_action,
    plan_committed,
    equipment_id,
    load_date,
    dispatch_date,
    dispatch_time,
    trip_type_id,
    load_type,
    trip_create_date,
    trip_create_time,
    upholstery_stage_loc,
    cubes_of_fill,
    xdock_after_trailer_in_door,
    number_of_drops,
    hauling_carrier,
    ship_from_name,
    ship_from_addr1,
    ship_from_addr2,
    ship_from_addr3,
    ship_from_city,
    ship_from_country_code,
    bol_print_flag,
    seal_number,
CAST(LEFT(load_id, CHARINDEX('-', load_id) - 1) AS INT) AS trip_nbr
FROM  t_load_master(nolock)  
-- 滚动1个月
where dispatch_date > DATEADD(MONTH, -1, GETDATE())
order by dispatch_date desc
  